#!/bin/sh -e
# Copyright (c) 2014 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
DESCRIPTION='Google Chrome browser, stable channel.'
. "${TARGETSDIR:="$PWD"}/chrome-common"

### Append to prepare.sh:
if [ "${DISTROAKA:-"$DISTRO"}" = 'arch' ]; then
    CHANNEL=''
else
    CHANNEL='stable'
fi
### append chrome-common
