#!/bin/sh -e
# Copyright (c) 2014 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Functions for installing things

# Installs a script to a destination, expanding any import calls into static
# insertions. If the file is a symlink, copies the symlink without modification.
# $1: the source script to process
# $2: the destination file or directory
# $3: optional additional commands to pass to sed (passed to -e)
installscript() {
    local src="$1" dst="$2"
    if [ -d "$dst" -o ! "${dst%/}" = "$dst" ]; then
        mkdir -p "$dst"
        dst="${dst%/}/${src##*/}"
    fi
    if [ -h "$src" ]; then
        cp -fPT "$src" "$dst"
        return
    fi
    awk -F '[, ]' '
    !ok && match($0, "^\. .*/parts/common") {
        ok = 1
        next
    }
    ok && /^ *import ([-a-z_]+[, ]*)+$/ {
        for (x=2; x<=NF; x++) {
            if ($x) {
                system("'"awk '/^$/{ok=1} ok' '$SCRIPTDIR/parts/\" \$x \"'"'");
            }
        }
        next
    }
    1' "$src" | sed -e "${3:-;}" > "$dst"
}

# Compares $RELEASE to the specified releases, assuming $DISTRODIR/releases is
# sorted oldest to newest. Every two parameters are considered criteria that are
# ORed together. The first parameter is the comparator, as provided to "test".
# The second parameter is the release to compare to. A comparison against a
# release from a different distro always fails. Since either $DISTRODIR/releases
# has to be readable or the release list has to be embedded, and RELEASE has to
# be set properly, this function should only be used in the context of targets.
# Returns non-zero if the release doesn't match
# Example:  release -ge quantal -ge wheezy
release() {
    if [ "$(($# % 2))" -ne 0 ]; then
        error 3 "invalid parameters to release(): $*"
    fi
    # Load up the list of releases; this will be replaced with a literal list
    local releases="`cat "$DISTRODIR/releases" 2>/dev/null`"
    if [ -z "$releases" ]; then
        error 3 "list of releases for $DISTRO not found"
    fi
    # End-of-word regex for awk
    local eow='([^a-z]|$)'
    local relnum="`echo "$releases" | awk "/^$RELEASE$eow/ {print NR; exit}"`"
    if [ -z "$relnum" ]; then
        error 3 "$RELEASE not found in $DISTRO"
    fi
    while [ "$#" -ge 2 ]; do
        local cmp="`echo "$releases" | awk "/^$2$eow/ {print NR; exit}"`"
        if [ -n "$cmp" ] && test "$relnum" "$1" "$cmp"; then
            return 0
        fi
        shift 2
    done
    return 1
}

