#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

set -e

# create the backup directory if not already created and
# create the gz compressed backup file in 
# /home/chronos/user/Downloads/crouton-backups/NAME/

usage="Description: This will create a compressed backup of the chroot.
The Default target is ~/Downloads/crouton-backups/name/
The File name will be name-yyyymmdd-hhmm.tar.gz

Usage: backup-chroot <options> name

Options:
	-t target - This will set the target to something other than the default.
		    Do not add a trailing slash at the end of this parameter"

if [ ! $1 = '' ] && [ "$2" = '' ]; then

	target="/home/chronos/user/Downloads/crouton-backups/$1"
	mkdir -p "$target"
	# .gz compression is always on in this mode, for frequent backups
	# this will save a lot of space.
	edit-chroot -f "$target"/"$1"-"`date '+%Y%m%d-%H%M'`".tar.gz -b "$1"

elif [ "$1" = '-t' ] && [ ! "$2" = '' ] && [ ! "$3" = '' ]; then

	target="$2"

	mkdir -p "$target"
	# .gz compression is always on in this mode, for frequent backups
	# this will save a lot of space.
	edit-chroot -f "$target"/"$3"-"`date '+%Y%m%d-%H%M'`".tar.gz -b "$3"

else

	echo "$usage"

fi
