#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

APPLICATION="${0##*/}"
BACKGROUND=''
BINDIR="`dirname "$0"`"
CHROOTS="`readlink -f "$BINDIR/../chroots"`"
KEYFILE=''
NAME=''
TARGET=''
USERNAME='1000'
NOLOGIN=''
SETUPSCRIPT='/prepare.sh'

USAGE="$APPLICATION [options] [command [args...]]

Enters an installed Debian-based chroot for running alongside Chromium OS.

By default, it will log into the primary user on the first chroot found.
You can specify a command and parameters to run instead of an interactive shell.

Options:
    -b          Fork and run the specified command silently in the background.
    -c CHROOTS  Directory the chroots are in. Default: $CHROOTS
    -k KEYFILE  Override the auto-detected encryption key location.
    -n NAME     Name of the chroot to enter. Default: first one found in CHROOTS
    -t TARGET   Only enter the chroot if it contains the specified TARGET.
    -u USERNAME Username (or UID) to log into. Default: 1000 (the primary user)
    -x          Does not log in, but directly executes the command instead.
                Note that the environment will be empty (sans TERM).
                Specify -x a second time to run the $SETUPSCRIPT script."

# Common functions
. "$BINDIR/../installer/functions"

# Process arguments
while getopts 'bc:k:n:t:u:x' f; do
    case "$f" in
    b) BACKGROUND='y';;
    c) CHROOTS="`readlink -f "$OPTARG"`";;
    k) KEYFILE="$OPTARG";;
    n) NAME="$OPTARG";;
    t) TARGET="$OPTARG";;
    u) USERNAME="$OPTARG";;
    x) NOLOGIN="$((NOLOGIN+1))"
       [ "$NOLOGIN" -gt 2 ] && NOLOGIN=2;;
    \?) error 2 "$USAGE";;
    esac
done
shift "$((OPTIND-1))"

# We need to run as root
if [ ! "$USER" = root -a ! "$UID" = 0 ]; then
    error 2 "$APPLICATION must be run as root."
fi

# We need a command if we specified to run in the background
if [ -n "$BACKGROUND" -a $# = 0 ]; then
    error 2 "A command must be specified in order to run in the background."
fi

# If -x is specified twice, our command is the setup script.
if [ "$NOLOGIN" = 2 ]; then
    if [ ! $# = 0 ]; then
        error 2 "A command cannot be specified with -xx."
    fi
    if [ -n "$BACKGROUND" ]; then
        error 2 "Cannot run the setup script in the background."
    fi
    set -- "$SETUPSCRIPT"
fi

# Select the first chroot available if one hasn't been specified
if [ -z "$NAME" ]; then
    haschroots=''
    for CHROOT in "$CHROOTS"/*; do
        if [ ! -d "$CHROOT/etc" -a ! -f "$CHROOT/.ecryptfs" ]; then
            continue
        fi
        haschroots='y'
        if [ -n "$TARGET" ]; then
            if ! grep -q "^$TARGET$" "$CHROOT/.crouton-targets" 2>/dev/null; then
                continue
            fi
        fi
        NAME="${CHROOT##*/}"
        break
    done
    if [ -z "$haschroots" ]; then
        error 1 "No chroots found in $CHROOTS"
    fi
    if [ -z "$NAME" ]; then
        error 1 "No chroots with target '$TARGET' found in $CHROOTS"
    fi
elif [ -n "$TARGET" ]; then
    if ! grep -q "^$TARGET$" "$CHROOTS/$NAME/.crouton-targets" 2>/dev/null; then
        error 1 "$CHROOTS/$NAME does not contain target '$TARGET'"
    fi
fi

# Make sure we always exit with echo on the tty.
addtrap "stty echo 2>/dev/null || true"

# Mount the chroot and update our CHROOT path
if [ -n "$KEYFILE" ]; then
    CHROOT="`sh -e "$BINDIR/mount-chroot" \
                                     -k "$KEYFILE" -p -c "$CHROOTS" "$NAME"`"
else
    CHROOT="`sh -e "$BINDIR/mount-chroot" -p -c "$CHROOTS" "$NAME"`"
fi

if [ ! "$NOLOGIN" = 2 ]; then
    echo "Entering $CHROOT..." 1>&2
fi

# In disk full situations, mount-chroot can be empty. Good time to check sanity.
if [ -z "$CHROOT" ]; then
    error 1 'Something is wrong with the crouton install. Please make sure you have
sufficient space available, then re-install the chroot and try again.'
fi

# Register the crash_reporter_wrapper to properly handle coredumps
if [ -f "$BINDIR/crash_reporter_wrapper" ]; then
    if ! sh -e "$BINDIR/crash_reporter_wrapper" register; then
        echo 'WARNING: Unable to register core dump handler.' 1>&2
    fi
fi

if [ -z "$CROUTON_NO_UNMOUNT" ]; then
    # Auto-unmount everything below and including the chroot upon exit
    addtrap "sh -e '$BINDIR/unmount-chroot' -yc '$CHROOTS' '$NAME' || true"
fi

# If our root is on an external disk we need to ensure USB device persistence is
# enabled otherwise we will lose the file-system after a suspend event.
if [ ! "${CHROOT#/media}" = "$CHROOT" ]; then
    for usbp in /sys/bus/usb/devices/*/power/persist; do
        echo 1 > "$usbp"
    done
fi

# Offer to run the setup script if it exists and yet we're logging in.
if [ -z "$NOLOGIN" -a -f "$CHROOT$SETUPSCRIPT" ]; then
    echo 'A chroot setup script still exists inside the chroot.' 1>&2
    echo 'The chroot may not be fully set up.' 1>&2
    response=''
    if tty -s; then
        echo -n 'Would you like to finish the setup? [Y/n] ' 1>&2
        read response
    fi
    if [ -z "$response" -o ! "${response#[Yy]}" = "$response" ]; then
        echo 'Preparing chroot environment...' 1>&2
        CROUTON_NO_UNMOUNT=1 sh -e "$BINDIR/enter-chroot" \
            -c "$CHROOTS" -n "$NAME" -xx
        echo 'Setup completed. Entering chroot...' 1>&2
    else
        echo 'Skipping setup. You will be prompted again next time.' 1>&2
    fi
fi

# Resolve USERNAME if it is a UID (and we're logging in)
passwd="$CHROOT/etc/passwd"
if [ -z "$NOLOGIN" ]; then
    if [ ! -r "$passwd" ]; then
        error 1 "$CHROOT doesn't appear to be a valid chroot."
    fi
    case "$USERNAME" in
    ''|*[!0-9]*)
        # Make sure the username exists
        if ! grep -q "^$USERNAME:" "$passwd"; then
            error 1 "User $USERNAME not found in $NAME"
        fi;;
     *)
        # Resolve the UID
        uid="$USERNAME"
        USERNAME="`awk -F: '$3=='"$uid"'{print $1; exit}' "$passwd"`"
        if [ -z "$USERNAME" ]; then
            error 1 "UID $uid not found in $NAME"
        fi
    esac
    # Detect the home directory and shell for the user
    CHROOTHOME="`awk -F: '$1=="'"$USERNAME"'"{print $6; exit}' "$passwd"`"
    CHROOTSHELL="`awk -F: '$1=="'"$USERNAME"'"{print $NF; exit}' "$passwd"`"
else
    CHROOTSHELL='/bin/sh'
fi

# Fix group numbers for critical groups to match Chromium OS. This is necessary
# so that users have access to shared hardware, such as video and audio.
gfile="$CHROOT/etc/group"
if [ -f "$gfile" ]; then
    for group in audio video usb:plugdev; do
        hostgroup="${group%:*}"
        chrootgroup="${group#*:}"
        gid="`awk -F: '$1=="'"$hostgroup"'"{print $3; exit}' '/etc/group'`"
        if [ -z "$gid" ]; then
            echo "Couldn't find $hostgroup group in Chromium OS!" 1>&2
            continue
        fi
        curgid="`awk -F: '$1=="'"$chrootgroup"'"{print $3; exit}' "$gfile"`"
        if [ "$gid" = "$curgid" ]; then
            continue
        elif [ -z "$curgid" ]; then
            echo "Couldn't find $chrootgroup group in chroot!" 1>&2
            continue
        fi
        echo "Changing $chrootgroup GID from $curgid to $gid..." 1>&2
        move="`awk -F: '$3=='"$gid"'{print $1; exit}' "$gfile"`"
        if [ -n "$move" ]; then
            ngid="$gid"
            while grep -q ":$ngid:" "$gfile"; do
                ngid="$((ngid+1))"
            done
            echo "Moving $move GID from $gid to $ngid..." 1>&2
            sed -i "s/:$gid:/:$ngid:/" "$gfile"
        fi
        sed -i "s/:$curgid:/:$gid:/" "$gfile"
    done
fi

# Save the chroot name to the chroot
echo "$NAME" > "$CHROOT/etc/crouton/name"

# Ensure $CHROOT/var/host exists.
mkdir -p "$CHROOT/var/host"

# Copy in the current Chromium OS version for reference
cp -f '/etc/lsb-release' "$CHROOT/var/host/"

# Copy the latest Xauthority into the chroot
cp -f "$XAUTHORITY" "$CHROOT/var/host/Xauthority"
chmod 444 "$CHROOT/var/host/Xauthority"
# Be backwards-compatible, just in case
if [ -f "$CHROOT/etc/X11/host-Xauthority" ]; then
    ln -sfT '/var/host/Xauthority' "$CHROOT/etc/X11/host-Xauthority"
fi

# Prepare chroot filesystem
# Soft-link resolv.conf so that updates are automatically propagated
ln -sf '/var/host/shill/resolv.conf' "$CHROOT/etc/resolv.conf"

# Sanity check of the timezone setting
localtime="$CHROOT/etc/localtime"
hostlocaltime='/var/host/timezone/localtime'
if [ -h "$localtime" ] && [ "`readlink "$localtime"`" = "$hostlocaltime" ]; then
    timezone="`readlink -m /var/lib/timezone/localtime || true`"
    if [ -z "$timezone" -o ! -e "$CHROOT$LOCALTIME" ]; then
        echo "\
WARNING: the timezone selected in Chromium OS does not exist inside the chroot.
To set the chroot's timezone, run the following: sudo dpkg-reconfigure tzdata" 1>&2
    else
        # Set /etc/timezone in chroot - fixes the clock in Unity
        echo "${timezone#/usr/share/zoneinfo/}" > "$CHROOT/etc/timezone"
    fi
fi

# Follows and fixes dangerous symlinks, returning the canonicalized path.
fixabslinks() {
    local p="$CHROOT/$1" c
    # Follow and fix dangerous absolute symlinks
    while c="`readlink -m "$p"`" && [ ! "$c" = "$p" ]; do
        p="$CHROOT${c#"$CHROOT"}"
    done
    echo "$p"
}

# Bind-mounts $1 into $CHROOT/${2:-"$1"} if $2 is not already mounted
# If $3 is specified, remounts with the specified options.
# If $1 starts with a -, it's considered options to the bind mount, and the rest
# of the parameters are shifted.
bindmount() {
    bindopts=''
    if [ ! "${1#"-"}" = "$1" ]; then
        bindopts="$1"
        shift
    fi
    local target="`fixabslinks "${2:-"$1"}"`"
    if mountpoint -q "$target"; then
        return 0
    fi
    mkdir -p "$target"
    mount --bind $bindopts "$1" "$target"
    if [ -n "$3" ]; then
        mount -i -o "remount,$3" "$target"
        if [ -n "$4" ]; then
            mount $4 "$target"
        fi
    fi
}

# Creates a tmpfs mount at $CHROOT/$1 with options $2 if not already mounted
tmpfsmount() {
    local target="`fixabslinks "$1"`"
    if mountpoint -q "$target"; then
        return 0
    fi
    mkdir -p "$target"
    mount -i -t tmpfs -o "rw${2:+,}$2" tmpfs "$target"
}

# If /var/run isn't mounted, we know the chroot hasn't been started yet.
if mountpoint -q "`fixabslinks '/var/run'`"; then
    firstrun=''
else
    firstrun='y'
fi

# Ensure the chroot is executable and writable by bind-mounting it to itself.
bindmount "$CHROOT" / rw,dev,exec,suid --make-unbindable
bindmount /dev
bindmount /dev/pts
bindmount /dev/shm
bindmount /sys
bindmount /sys/fs/fuse/connections
bindmount /tmp /tmp exec
bindmount /proc
tmpfsmount /var/run 'noexec,nosuid,mode=0755,size=10%'
tmpfsmount /var/run/lock 'noexec,nosuid,nodev,size=5120k'
bindmount /var/run/dbus /var/host/dbus
bindmount /var/run/shill /var/host/shill
bindmount /var/lib/timezone /var/host/timezone
for m in /lib/modules/*; do
    if [ -d "$m" ]; then
        bindmount '-o ro' "$m"
    fi
done

# Add a shm symlink to our new /var/run
ln -sfT /dev/shm "`fixabslinks '/var/run'`/shm"

# Add a /run/udev symlink for later versions of udev
ln -sfT /dev/.udev "`fixabslinks '/var/run'`/udev"

# Bind-mount /media, specifically the removable directory
destmedia="`fixabslinks '/var/host/media'`"
if [ -d "$CHROOT/media" ] && ! mountpoint -q "$destmedia"; then
    mount --make-shared /media
    mkdir -p "$destmedia"
    ln -sf "/var/host/media/removable" "$CHROOT/media/"
    mount --rbind /media "$destmedia"
fi

# Bind-mount ~/Downloads if we're logged in as a user
localdownloads='/home/chronos/user/Downloads'
if [ -z "$NOLOGIN" -a -n "$CHROOTHOME" -a -d "$localdownloads" ]; then
    bindmount "$localdownloads" "$CHROOTHOME/Downloads" exec
fi

# To run silently, we override the env command to launch a background process,
# and move the trap code to happen there.
if [ -n "$BACKGROUND" ]; then
    env() {
        local stdin=''
        [ ! -t 0 ] && stdin="`readlink -m /dev/stdin`"
        (
            trap '' INT HUP
            trap "$TRAP" 0
            [ -n "$stdin" ] && exec < "$stdin"
            [ -t 1 ] && exec  > /dev/null
            [ -t 2 ] && exec 2> /dev/null
            /usr/bin/env "$@"
        ) &
    }
fi

# Launch the system dbus unless we are entering a basic shell.
if [ ! "$NOLOGIN" = 1 ] && grep -q '^root:' "$passwd" 2>/dev/null; then
    # Try to detect the dbus user by parsing its configuration file
    # If it fails, or if the user does not exist, `id -un '$dbususer'`
    # will fail, and we fallback on a default user name ("messagebus")
    dbususer="`echo "cat /busconfig/user/text()" \
        | xmllint --shell "$CHROOT/etc/dbus-1/system.conf" 2>/dev/null \
        | grep '^[a-z][-a-z0-9_]*$' || true`"
    env -i chroot "$CHROOT" su -s '/bin/sh' -c "
        if ! hash dbus-daemon 2>/dev/null; then
            exit 0
        fi
        dbususer='$dbususer'"'
        pidfile="/var/run/dbus/pid"
        if [ -f "$pidfile" ]; then
            if grep -q "^dbus-daemon" "/proc/`cat "$pidfile"`/cmdline" \
                    2>/dev/null; then
                exit 0
            fi
            rm -f "$pidfile"
        fi
        mkdir -p /var/run/dbus
        dbususer="`id -un "$dbususer" 2>/dev/null || echo "messagebus"`"
        dbusgrp="`id -gn "$dbususer" 2>/dev/null || echo "messagebus"`"
        chown "$dbususer:$dbusgrp" /var/run/dbus
        dbus-daemon --system --fork' - root
fi

# Start the chroot and any specified command
ret=0
if [ -n "$NOLOGIN" ]; then
    env -i TERM="$TERM" chroot "$CHROOT" "$@" || ret=$?
    # Handle the return value when running the setup script.
    if [ "$NOLOGIN" = 2 ]; then
        # If it succeeded yet still exists, run it again.
        if [ "$ret" = 0 -a -f "$CHROOT$SETUPSCRIPT" ]; then
            sh -e "$BINDIR/unmount-chroot" -yxc "$CHROOTS" "$NAME"
            # We don't need to return from this.
            exec sh -e "$BINDIR/enter-chroot" -c "$CHROOTS" -n "$NAME" -xx
        elif [ ! "$ret" = 0 ]; then
            error "$ret" 'Failed to complete chroot setup.'
        fi
    fi
else
    # Run rc.local
    if [ -n "$firstrun" -a -x "$CHROOT/etc/rc.local" ]; then
        env -i chroot "$CHROOT" su -s '/bin/sh' -c \
            'exec /etc/rc.local >/dev/null 2>/dev/null </dev/null' - root \
            || ret=$?
        if [ ! "$ret" = 0 ]; then
            echo "WARNING: /etc/rc.local failed with code $ret" 1>&2
            ret=0
        fi
    fi

    if [ $# = 0 ]; then
        env -i TERM="$TERM" chroot "$CHROOT" su - "$USERNAME" || ret=$?
    else
        # Escape out the command
        cmd="export SHELL='$CHROOTSHELL';"
        for param in "$@"; do
            cmd="$cmd'`echo -n "$param" | sed "s/'/'\\\\\\''/g"`' "
        done
        env -i TERM="$TERM" chroot "$CHROOT" \
            su -s '/bin/sh' -c "$cmd" - "$USERNAME" \
            || ret=$?
    fi
fi

# We don't want to trap for this proccess if we're running in the background
if [ -n "$BACKGROUND" ]; then
    trap - INT HUP 0
fi

# Cleanup all happens in the exit trap
exit $ret
