#!/bin/sh -e
# Copyright (c) 2024 Your Name or Organization. All rights reserved.
# This script is provided under the MIT License:
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES, OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# A shortcut script to control device brightness.
# Usage:
#    brightness [b|k] [up|down|# [instant]]

# Choose the device
device='Screen'
nokbd=''
case "$1" in
k*) device='Keyboard'
    nokbd='echo "Command not supported with keyboard backlight." 1>&2; exit 1' 
    shift;;
b*) shift;;
esac

# Handle user command
print=''
postcmd=''
case "$1" in
u*) precmd='Increase';;
d*) precmd='Decrease';;
[0-9]*) eval $nokbd;
    precmd='Set'; postcmd="Percent double:$1 int32:${2:-"1"}${2:+"2"}";;
*) eval $nokbd; precmd='Get'; postcmd='Percent'; print='--print-reply';;
esac

host-dbus dbus-send --system --dest=org.chromium.PowerManager \
          --type=method_call $print /org/chromium/PowerManager \
          org.chromium.PowerManager.${precmd}${device}Brightness${postcmd} | {
    read -r junk
    read -r double percent
    if [ -n "$print" ]; then
        echo "${percent%.*}"
    fi
}

exit 0

