#!/bin/sh -e
# Copyright (c) 2014 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# Helper script for launching services normally managed by upstart.
# Called during session's XDG autostart.

ARCH="`/usr/local/bin/croutonversion -a`"
RELEASE="`/usr/local/bin/croutonversion -r`"

# Fix arch to the correct format for /usr/lib triples
case "$ARCH" in
x86 | i?86) ARCH="i386";;
x86_64 | amd64) ARCH="x86_64";;
arm*) ARCH="armhf";;
esac

# Launch window-stack-bridge for Unity HUD support
if [ "$RELEASE" = 'saucy' -o "$RELEASE" = 'trusty' ]; then
    window_stack_bridge="/usr/lib/$ARCH-linux-gnu/hud/window-stack-bridge"
    if [ -x "$window_stack_bridge" ]; then
        "$window_stack_bridge" &
    fi
fi

# Launch unity-panel-service and any indicators in /usr/share/upstart/sessions.

# Both saucy and trusty need to launch unity-panel-service.
if [ "$RELEASE" = 'saucy' -o "$RELEASE" = 'trusty' ]; then
    /usr/lib/unity/unity-panel-service >/dev/null 2>&1 &
fi

# If on trusty, indicators also need to be started.
if [ "$RELEASE" = 'trusty' ]; then
    for f in /usr/share/upstart/sessions/*.conf; do
        if grep -q '^start on.* indicator-services-start' "$f"; then
            # Parse out exec and launch.
            # Assume no space in path, and run without args.
            exec_cmd="`awk '/^exec/{print $2; exit}' "$f"`"
            $exec_cmd &
        fi
    done
fi
