#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

USAGE="${0##*/} next|prev|cros
Cycles through running graphical chroots.
\"cros\" switches back to Chromium OS."

case "$1" in
[Cc]*) cmd='select 0';;
[Pp]*) cmd='prev';;
[Nn]*) cmd='next';;
*) echo "$USAGE" 1>&2; exit 2;;
esac

# If we're using Xephyr, run ratpoison
xmethod="`readlink -f '/etc/X11/xinit/xserverrc'`"
xmethod="${xmethod##*-}"
if [ "$xmethod" = 'xephyr' ]; then
    exec /usr/local/bin/host-x11 ratpoison -c "$cmd"
fi

# cros: Switch to VT1
if [ "$cmd" = 'select 0' ]; then
    exec chvt 1
fi

# Otherwise, determine current tty and X11 ttys
curtty="`cat '/sys/class/tty/tty0/active'`"
seltty=''
prevtty=''
for tty in `ps -CX -CXorg -otname= | sort`; do
    # On some systems, the tty of Chromium OS cannot be determined and returns ?
    if [ "$tty" = '?' ]; then
        tty='tty1'
    fi
    if [ "$cmd" = 'next' -a -z "$seltty" ]; then
        seltty="$tty"
    fi
    if [ -z "$curtty" ]; then
        seltty="$tty"
        break
    elif [ "$tty" = "$curtty" ]; then
        # Make the tty selection.
        if [ "$cmd" = 'prev' ]; then
            seltty="$prevtty"
        else
            curtty=''
        fi
    fi
    prevtty="$tty"
done
if [ -z "$seltty" ]; then
    seltty="$tty"
fi

# If we have a tty and it's not the same as the current one, switch
if [ -n "$seltty" -a ! "$seltty" = "$curtty" ]; then
    exec chvt "${seltty#tty}"
fi
