#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

USAGE="${0##*/} next|prev|cros|list|#
Cycles through running graphical chroots.
    next: switch to the next display
    prev: switch to the previous display
    cros: switch directly to Chromium OS
    list: list all of the active displays and the associated chroot name
    #: switch to the nth item in the list, zero-indexed
    :#: switch directly to the chroot owning the specified display number"

case "$1" in
[Ll]*) cmd='l';;
[Cc]*) cmd='0';;
[Pp]*) cmd='p';;
[Nn]*) cmd='n';;
:*) cmd=":$((${1#:}))";;
[0-9]*) cmd="$(($1))";;
*) echo "$USAGE" 1>&2; exit 2;;
esac

export XAUTHORITY=''

# Prepare display list for easier looping
displist=''
for disp in /tmp/.X*-lock; do
    disp="${disp#*X}"
    disp=":${disp%-lock}"
    # Only add VT-based chroots here
    if [ "$disp" = ':0' ]; then
        continue
    elif DISPLAY="$disp" xprop -root 'XFree86_VT' 2>/dev/null \
            | grep -q 'INTEGER'; then
        displist="$displist $disp"
    fi
done
# List windows on :0. Includes aura
winlist="`host-x11 croutonwmtools list nim | sort | awk '{ printf $NF " " }'`"

# Combine the two
fulllist="$winlist$displist"

# Figure out the current display number
tty="`cat '/sys/class/tty/tty0/active'`"
if [ "$tty" = 'tty1' ]; then
    # Either in Chromium OS, xephyr chroot, or window. Active window is starred.
    for disp in $winlist; do
        if [ "${disp%"*"}" != "$disp" ]; then
            curdisp="$disp"
            break
        fi
    done
else
    # Poll the displays to figure out which one owns this VT
    curdisp=''
    for disp in $displist; do
        if DISPLAY="$disp" xprop -root 'XFree86_VT' 2>/dev/null \
                | grep -q " ${tty#tty}\$"; then
            curdisp="$disp"
            break
        fi
    done
    if [ -z "$curdisp" ]; then
        curdisp="$tty"
    fi
fi

# List the displays if requested
if [ "$cmd" = 'l' ]; then
    chromiumos='Chromium OS'
    if [ -r '/var/host/lsb-release' ]; then
        chromiumos="`awk -F= '/_RELEASE_NAME=/{print $2}' \
                             '/var/host/lsb-release'`"
    fi
    host-x11 croutonwmtools list nim | sort | while read line; do
        disp="${line##* }"
        line="${line% *}"
        number='0'
        if [ "${line#Xephyr}" != "$line" ]; then
            number="${line#*:}"
            number="${line%%.*}"
            if [ "${number#[0-9]}" = "$number" ]; then
                number='0'
            fi
        fi
        if [ "$disp" = "$curdisp" ]; then
            echo -n "$number*"
        else
            echo -n "$number "
        fi
        if [ "$line" = 'aura_root_0' ]; then
            echo " $chromiumos"
        else
            echo " $line"
        fi
    done
    for disp in $displist; do
        if [ "$disp" = "$curdisp" ]; then
            echo -n "${disp#:}*"
        else
            echo -n "${disp#:} "
        fi
        name="`DISPLAY="$disp" xprop -root CROUTON_NAME 2>/dev/null`"
        if [ "${name%\"}" != "$name" ]; then
            name="${name%\"}"
            name="${name#*\"}"
        else
            name="Unknown"
        fi
        echo " $name"
    done
    exit 0
fi

# Determine the target display
if [ -n "${cmd#[pn]}" ]; then
    if [ "${cmd#:}" != "$cmd" ]; then
        destdisp="$cmd"
    else
        i=0
        for disp in $fulllist; do
            if [ "$i" -eq "$cmd" ]; then
                break
            fi
            i="$((i+1))"
        done
        destdisp="$disp"
    fi
elif [ "${curdisp#tty}" != "$curdisp" ]; then
    destdisp='0'
elif [ "$cmd" = 'p' ]; then
    destdisp="${fulllist##* }"
    for disp in $fulllist; do
        if [ "$disp" = "$curdisp" ]; then
            break
        fi
        destdisp="$disp"
    done
elif [ "$cmd" = 'n' ]; then
    destdisp=''
    for disp in $fulllist; do
        if [ -n "$destdisp" ]; then
            destdisp="$disp"
            break
        elif [ "$disp" = "$curdisp" ]; then
            destdisp="${fulllist%% *}"
        fi
    done
else
    destdisp='0'
fi

# No-op on no-op
if [ "$destdisp" = "$curdisp" ]; then
    exit 0
fi

# Determine if the target display is on a VT
if [ "${destdisp#:}" = "$destdisp" ]; then
    dest="${destdisp%"*"}"
else
    dest="`DISPLAY="$destdisp" xprop -root 'XFree86_VT' 2>/dev/null`"
    dest="vt${dest##* }"
    if [ "${dest#vt[0-9]}" = "$dest" ]; then
        dest="vt1"
    fi
fi

# Make sure tap-to-click is disabled
if hash xinput 2>/dev/null; then
    for id in `host-x11 xinput --list --id-only`; do
        host-x11 xinput set-prop "$id" 'Tap Paused' 0 2>/dev/null || true
    done
fi

# Raise the right window after chvting, so that it can update
if [ "${dest#vt}" = "$dest" ]; then
    if [ "$tty" != 'tty1' ]; then
        chvt 1
        sleep .1
    fi
    host-x11 croutonwmtools raise "$dest"
else
    chvt "${dest#vt}"
fi

# Wait a flip and then refresh the display for good measure
if hash xrefresh 2>/dev/null; then
    sleep .1
    if [ "${destdisp#:}" = "$destdisp" ]; then
        host-x11 xrefresh
    else
        DISPLAY="$destdisp" xrefresh
    fi
fi
exit 0
