#!/bin/sh -e
# Copyright (c) 2024 Your Name or Organization. All rights reserved.
# This script is provided under the MIT License:
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES, OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Wrapper for scripts that shouldn't be launched as root.
# Symlink to launch the application with the same name in /usr/bin/
# Launch directly with a parameter to launch that executable
# Launch directly with a blank or - first parameter and a word to just check and
# exit with an exit code, printing out the second parameter as the app name.

APPLICATION="${0##*/}"
if [ "$APPLICATION" = 'crouton-noroot' ]; then
    if [ -z "$1" -o "$1" = '-' -o "$1" = '--' ]; then
        APPLICATION=''
    else
        APPLICATION="$1"
        shift
    fi
else
    APPLICATION="/usr/bin/$APPLICATION"
fi

if [ "$USER" = root -o "$UID" = 0 ]; then
    app="${APPLICATION:-"$2"}"
    echo "Do not launch ${app##*/} as root inside the chroot." 1>&2
    exit 2
elif [ -z "$APPLICATION" ]; then
    exit 0
fi

exec "$APPLICATION" "$@"

