#!/bin/sh -e
# Copyright (c) 2014 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

set -e

VERBOSE=

ADDRESS="$1"
PATTERN="$2"
PIDS="${3:-"`pgrep nacl_helper`"}"

MATCH=""

# Iterate over all NaCl helper processes
for pid in $PIDS; do
    if [ -n "$VERBOSE" ]; then echo "pid:$pid" 1>&2; fi
    # Find candidate mappings
    file="`awk '$1 ~ /^[0-9a-f]*'"$ADDRESS"'-/ && $2 == "rw-s" \
             && $6 ~ /\/shm\/.com.google.Chrome/ { print $6 }
    ' "/proc/$pid/maps"`"
    if [ -n "$VERBOSE" ]; then echo "file:$file" 1>&2; fi
    if [ -z "$file" ]; then
        continue
    fi

    # Iterate over mappings, and check signature
    for fd in "/proc/$pid/fd"/*; do
        link="`readlink "$fd"`"
        link="${link% (deleted)}"
        if [ "$link" = "$file" ]; then
            # Check if signature matches
            pattern="`od -An -t x1 -N8 "$fd" | tr -d ' '`"
            if [ -n "$VERBOSE" ]; then echo "FD:$fd ($pattern)" 1>&2; fi
            if [ "$pattern" = "$PATTERN" ]; then
                # Second match? This should never happen
                if [ -n "$MATCH" ]; then
                    echo -n "-1:ambiguous"
                    exit 1
                fi
                MATCH="$pid:$fd"
            fi
        fi
    done
done

if [ -n "$MATCH" ]; then
    echo -n "$MATCH"
    exit 0
else
    echo -n "-1:no match"
    exit 1
fi
