#!/bin/sh -e
# Copyright (c) 2014 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Changes the resolution of the current display, taking the closest,
# smaller, available resolution in xrandr.
# If no smaller resolution is available, pick the closest one.
# Outputs the applied resolution

set -e

if [ -z "$1" -o -z "$2" ]; then
   echo "Usage: $0 width height" 1>&2
   exit 2
fi

TARGETW="$1"
TARGETH="$2"

# This assumes modes have "canonical" names, in the form "<w>x<h>[_<r>]"
res="`xrandr | awk '
    function abs(x) { return x > 0 ? x : -x }
    BEGIN {
        tw='"$TARGETW"'
        th='"$TARGETH"'
        oversize_penalty = 1000000
    }
    $1 ~ /[0-9]+x[0-9]+/ {
        res = $1; sub(/_[0-9]+/, "", res)
        w = res; sub(/x[0-9]*/, "", w); w = int(w)
        h = res; sub(/[0-9]*x/, "", h); h = int(h)
        score = abs(tw-w) + abs(th-h)
        if (w > tw) score += oversize_penalty
        if (h > th) score += oversize_penalty
        if (!cmode || score < cscore) {
            cmode = $1
            cscore = score
        }
    }
    END {
        if (!cmode) exit 1
        print cmode
    }
'`"

if [ -z "$res" ]; then
   echo "Cannot find resolution" 1>&2
   exit 1
fi

xrandr -s "$res" 2>/dev/null
echo -n "$res"
