#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# Provides a wrapper around gnome-session to allow gnome-session based
# desktop environments to work with crouton nicely

USAGE="${0##*/} [session]
A wrapper around gnome-session that can be passed to xinit.
Provide the session type in the DESKTOP_SESSION variable, 
or as an optional session argument.

Examples:
(launch GNOME from crosh with session in DESKTOP_SESSION)
DESKTOP_SESSION=gnome xinit /etc/X11/xinit/xinitrc ${0##*/}

(launch Unity from an xterm with session as an argument)
${0##*/} ubuntu"

export DESKTOP_SESSION="${DESKTOP_SESSION:-"$1"}"
if [ -z "$DESKTOP_SESSION" ]; then
    echo "$USAGE" 1>&2
    exit 2
fi

if [ -z "$DISPLAY" ]; then
    exec xinit /etc/X11/xinit/xinitrc "$0"
else
    exec gnome-session --session="$DESKTOP_SESSION"
fi
