#!/bin/sh -eu
CLUTTER_BACKEND=wayland
DISPLAY=:0
GDK_BACKEND=x11
SCALE=1
WAYLAND_DISPLAY=wayland-0
XDG_RUNTIME_DIR=/var/run/chrome

export CLUTTER_BACKEND
export DISPLAY SCALE
export GDK_BACKEND
export WAYLAND_DISPLAY
export XDG_RUNTIME_DIR

# Allow user to define their own variables
# SOMMELIER_ACCELERATORS and GL_DRIVER_PATH

if [ -z "$SOMMELIER_ACCELERATORS" ]; then
    SOMMELIER_ACCELERATORS="Super_L,<Control>space,<Alt>space,<Alt>bracketleft,<Alt>bracketright,<Alt>minus,<Alt>equal"
if

if [ -z "$GL_DRIVER_PATH" ]; then
    # Find the architecture specific libgl1-mesa-dri library location
    GL_DRIVER_PATH=$(grep '\/dri$' /var/lib/dpkg/info/libgl1-mesa-dri*list | head -1 )
if

SOMM=$(pidof sommelier 2> /dev/null)
if [ -z "$SOMM" ]; then
    sommelier -X --x-display=$DISPLAY --scale=$SCALE \
       --glamor --drm-device=/dev/dri/renderD128  \
       --virtwl-device=/dev/null --shm-driver=noop \
       --data-driver=noop --display=$WAYLAND_DISPLAY \
       --xwayland-path=/usr/bin/Xwayland \
       --accelerators=$SOMMELIER_ACCELERATORS \
       --xwayland-gl-driver-path=$GL_DRIVER_PATH \
       --no-exit-with-child \
       /bin/sh -c "/usr/local/etc/sommelierrc" > /tmp/sommelier.log 2>&1 &
    sleep 3
fi

SOMM=$(pidof sommelier 2> /dev/null)
if [ ! -z "$SOMM" ]; then
  echo "sommelier process $SOMM is running"
else
  echo "sommelier failed to start"
  exit 1
fi

if [ "$1" ]; then
    exec "$@" >> /tmp/sommelier.log 2>&1
fi

exit 0
