#!/bin/sh -eu
# Copyright (c) 2021 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

export CLUTTER_BACKEND=wayland
export GDK_BACKEND=x11
export SCALE="${SCALE:-1}"
export WAYLAND_DISPLAY=wayland-0
export XDG_RUNTIME_DIR=/var/run/chrome

# This serves as an analogue of the Xserver log file
SOMMELIER_LOG="/tmp/crouton-sommelier.log"

# Allow user to define their own variables
# WAITFORX, SOMMELIER_ACCELERATORS and GL_DRIVER_PATH

# Time to wait for Xwayland to start
DEFAULT_WAITFORX=3
WAITFORX="${WAITFORX:-${DEFAULT_WAITFORX}}"

DEFAULT_SOMMELIER_ACCELERATORS="Super_L,<Control>space,<Alt>space,<Alt>bracketleft,<Alt>bracketright,<Alt>minus,<Alt>equal"
SOMMELIER_ACCELERATORS="${SOMMELIER_ACCELERATORS:-${DEFAULT_SOMMELIER_ACCELERATORS}}"

# Find the architecture specific libgl1-mesa-dri library location
FOUND_DRIVER_PATH="$(grep '[/]dri$' /var/lib/dpkg/info/libgl1-mesa-dri*list | head -n1 )"
GL_DRIVER_PATH="${GL_DRIVER_PATH:-${FOUND_DRIVER_PATH}}"

SOMMELIER="$(pidof sommelier.real 2> /dev/null || true)"
if [ -z "$SOMMELIER" ]; then
    # Since sommelier is *not* running check for the next available
    # DISPLAY. Code taken from crouton's 'xinit' script
    disp=0
    while [ -S "/tmp/.X11-unix/X$disp" ]; do
         disp=$(($disp+1))
    done
    export DISPLAY=":${disp}"

    /usr/local/lib/sommelier.real -X --x-display="$DISPLAY" \
       --scale="$SCALE" \
       --glamor \
       --virtwl-device=/dev/null --shm-driver=noop \
       --data-driver=noop --display="$WAYLAND_DISPLAY" \
       --xwayland-path=/usr/bin/Xwayland \
       --accelerators="$SOMMELIER_ACCELERATORS" \
       --xwayland-gl-driver-path="$GL_DRIVER_PATH" \
       --no-exit-with-child \
       /bin/sh -c "/etc/crouton/sommelierrc" > "$SOMMELIER_LOG" 2>&1 &
     
    # wait for the X server to start
    SOMMELIER="$!"
    waited=0
    while [ "$waited" -le "$WAITFORX" ]; do
        if [ -S "/tmp/.X11-unix/X$disp" ]; then
            echo "Waited for $waited seconds for Xwayland to start." >> "$SOMMELIER_LOG" 2>&1 &
            break
        fi
        sleep 1
        waited="$(($waited + 1))"
    done
    if [ ! -S "/tmp/.X11-unix/X$disp" ]; then
        echo "Xwayland failed to start" 1>&2
        exit 1
    fi
else
    # set the DISPLAY to that of the running sommelier
    eval "export $(cat /proc/${SOMMELIER}/environ | tr '\0' '\n' | grep '^DISPLAY=')"
fi

if [ "$#" -gt 0 ]; then
    exec "$@" >> "$SOMMELIER_LOG" 2>&1
fi

exit 0
