#!/bin/sh -eu
# Copyright (c) 2021 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

export CLUTTER_BACKEND=wayland
export DISPLAY=:0
export GDK_BACKEND=x11
export SCALE=1
export WAYLAND_DISPLAY=wayland-0
export XDG_RUNTIME_DIR=/var/run/chrome

# Allow user to define their own variables
# SOMMELIER_ACCELERATORS and GL_DRIVER_PATH

DEFAULT_SOMMELIER_ACCELERATORS="Super_L,<Control>space,<Alt>space,<Alt>bracketleft,<Alt>bracketright,<Alt>minus,<Alt>equal"
SOMMELIER_ACCELERATORS="${SOMMELIER_ACCELERATORS:=$DEFAULT_SOMMELIER_ACCELERATORS}"

# Find the architecture specific libgl1-mesa-dri library location
FOUND_DRIVER_PATH="$(grep '\/dri$' /var/lib/dpkg/info/libgl1-mesa-dri*list | head -1 )"
GL_DRIVER_PATH="${GL_DRIVER_PATH:=$FOUND_DRIVER_PATH}"

SOMMELIER="$(pidof sommelier.real 2> /dev/null || true)"
if [ -z "$SOMMELIER" ]; then
    /usr/local/lib/sommelier.real -X --x-display="$DISPLAY" --scale="$SCALE" \
       --glamor --drm-device=/dev/dri/renderD128  \
       --virtwl-device=/dev/null --shm-driver=noop \
       --data-driver=noop --display="$WAYLAND_DISPLAY" \
       --xwayland-path=/usr/bin/Xwayland \
       --accelerators="$SOMMELIER_ACCELERATORS" \
       --xwayland-gl-driver-path="$GL_DRIVER_PATH" \
       --no-exit-with-child \
       /bin/sh -c "/etc/crouton/sommelierrc" > /tmp/crouton-sommelier.log 2>&1 &
    sleep 3
fi

SOMMELIER="$(pidof sommelier.real 2> /dev/null || true)"
if [ ! -z "$SOMMELIER" ]; then
  echo "sommelier process $SOMMELIER is running"
else
  echo "sommelier failed to start"
  exit 1
fi

if [ "$#" -gt 0 ]; then
    exec "$@" >> /tmp/crouton-sommelier.log 2>&1
fi

exit 0
