#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Launches Unity; will fall back to Unity-2D on supported releases

exec gnome-session-wrapper ubuntu
