#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Adds a :# to the xinit command line, where # is the first available display
# number. Also adds the -- to the command line and references the global
# xserverrc if it isn't already there.  By putting this in /usr/local/bin, PATH
# will prefer it and scripts that call xinit will automagically work.

croutonwm='/usr/local/bin/croutonwm'
if [ -x "$croutonwm" ]; then
    . "$croutonwm"
fi

xserverrc='/etc/X11/xinit/xserverrc'
dash='--'
for arg in "$@"; do
    if [ -z "$dash" ]; then
        # Check if there's a xserverrc specified.
        if [ ! "${arg#/}" = "$arg" ]; then
            xserverrc=''
        fi
        break
    elif [ "$arg" = '--' ]; then
        dash=
    fi
done

disp=0
while [ -f "/tmp/.X$disp-lock" ]; do
    disp=$((disp+1))
done

# Function to exec the parameters when the display has been created.
queuelaunch() {
    (while sleep 1; do
        if [ -S "/tmp/.X11-unix/X$disp" ]; then
            DISPLAY=":$disp" exec "$@" >/dev/null 2>&1
        fi
    done) &
}

# Launch the powerd poker daemon
queuelaunch croutonpowerd --daemon

# Launch touchegg if it is requested.
toucheggconf='/etc/touchegg.conf'
if [ -f "$toucheggconf" ]; then
    mkdir -p "$HOME/.config/touchegg"
    ln -sf "$toucheggconf" "$HOME/.config/touchegg/"
    queuelaunch touchegg
fi

exec /usr/bin/xinit "$@" $dash $xserverrc ":$disp"
