#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Adds a :# to the xinit command line, where # is the first available display
# number. Also adds the -- to the command line and references the global
# xserverrc if it isn't already there.  By putting this in /usr/local/bin, PATH
# will prefer it and scripts that call xinit will automagically work.

# Launch the global window manager if needed
xmethod="`readlink -f '/etc/X11/xinit/xserverrc'`"
xmethod="${xmethod##*-}"
croutonwm='/usr/local/bin/croutonwm'
if [ "$xmethod" = 'xephyr' -a -x "$croutonwm" ]; then
    "$croutonwm" --fork
fi

# Launch the clipboard synchronization daemon
croutonclip='/usr/local/bin/croutonclip'

if [ -x "$croutonclip" ] && ! pgrep -x croutonclip >/dev/null; then
    env -i CROUTON="CORE" "$croutonclip" <&- &
fi

xserverrc='/etc/X11/xinit/xserverrc'
dash='--'
for arg in "$@"; do
    if [ -z "$dash" ]; then
        # Check if there's a xserverrc specified.
        if [ ! "${arg#/}" = "$arg" ]; then
            xserverrc=''
        fi
        break
    elif [ "$arg" = '--' ]; then
        dash=
    fi
done

disp=0
while [ -f "/tmp/.X$disp-lock" ]; do
    disp=$((disp+1))
done

exec /usr/bin/xinit /usr/local/bin/croutonxinitrc-wrapper "$@" $dash $xserverrc ":$disp"
