#!/bin/sh -e
# Copyright (c) 2014 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Runs the specified X11 application in its own X server in Chromium OS.

. "`dirname "$0"`/../installer/functions"
xiwicmd="`readlink -f "$0"`"

if [ "$#" = 0 ]; then
    echo "Usage: ${0##*/} APPLICATION [PARAMETERS ...]
Launches a windowed session in Chromium OS for any graphical application.
All parameters are passed to the specified application.

A default window manager will full-screen all windows, unless APPLICATION begins
with 'start'. You can cycle through multiple windows inside the application via
Ctrl-Alt-Tab/Ctrl-Alt-Shift-Tab, or close them via Ctrl-Alt-Shift-Escape.
If APPLICATION begins with 'start' but you still want to use the default window
manager, specify the full path of the application." 1>&2
    exit 2
elif [ "$1" = '/' ]; then
    shift 1
    xsetroot -cursor_name left_ptr
    if [ "${1#start}" = "$1" ]; then
        i3 -c "/etc/crouton/xiwi.conf" &
        # Wait for i3 to launch
        xprop -spy -root | grep -q _NET_ACTIVE_WINDOW
        # Launch the window title monitoring daemon
        xprop -spy -notype -root 0i ' $0\n' '_NET_ACTIVE_WINDOW' 2>/dev/null | {
            monpid=''
            monwid=''
            while read _ wid; do
                if [ "$wid" = "$monwid" ]; then
                    continue
                fi
                if [ -n "$monpid" ]; then
                    kill "$monpid" 2>/dev/null
                fi
                monwid="$wid"
                xprop -spy -notype -id "$wid" 'WM_NAME' 2>/dev/null | {
                    while read _ title; do
                        title="${title%\"}"
                        title="`cat /etc/crouton/name`/$1: ${title#*\"}"
                        xprop -root -f CROUTON_NAME 8s -set CROUTON_NAME "$title"
                        ret="`{ echo -n 'C'; croutoncycle l; } | websocketcommand`"
                    done
                } &
                monpid="$!"
            done
            if [ -n "$monpid" ]; then
                kill "$monpid" 2>/dev/null
            fi
        } &
    fi
    exec "$@"
else
    export XMETHOD=xiwi
    exec /usr/local/bin/xinit "$xiwicmd" / "$@"
fi
