#!/bin/sh -e
# Copyright (c) 2014 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Runs the specified X11 application in its own X server in Chromium OS.

if [ "$#" = 0 ]; then
    echo "Usage: $0 cmd params" 1>&2
    exit 2
elif [ "$1" = '/' ]; then
    shift 1
    genwindowname="`cat /etc/crouton/name`/$1: \`\
        ratpoison -c 'windows %s%t' | sed -n '/^\*/s/^.//p'\`"
    "$@" &
    exec /usr/bin/ratpoison -f /dev/stdin <<WMRC
        escape C-S-M-Escape
        set border 0
        startup_message off
        addhook newwindow exec \
            xprop -root -f CROUTON_NAME 8s -set CROUTON_NAME "$genwindowname"
        addhook switchwin exec \
            xprop -root -f CROUTON_NAME 8s -set CROUTON_NAME "$genwindowname"
        addhook deletewindow exec sleep 1 \
            && ! ratpoison -c 'windows %%' | grep -q '%' \
            && ratpoison -c quit || true
WMRC
fi
export XMETHOD=xiwi
exec /usr/local/bin/xinit "`readlink -f "$0"`" / "$@"
