#!/bin/sh -e
# Copyright (c) 2014 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This is a distro-specific bootstrap script, sourced from main.sh, and as such
# has access to all of the variables set by main.sh, namely $tmp (the temporary
# directory), $INSTALLERDIR/$DISTRO, $RELEASE, $ARCH, and $MIRROR.

# This code is loosely based on a script found on the Arch Linux Wiki:
# https://wiki.archlinux.org/index.php/Install_from_Existing_Linux

REPOS='core community extra'

if [ "$ARCH" = 'armv7h' ]; then
    REPOS="$REPOS alarm aur"
fi

# Packages to install in the bootstrap chroot. Dependencies are automatically
# fetched, but finding a suitable virtual package is not supported, so we have
# to list them manually:
# - bash provides sh
# - gawk provides awk
PACKAGES_BOOTSTRAP="bash gawk grep pacman sed util-linux"

LIST="$tmp/list"
FETCHDIRDB="$tmp/db"
FETCHDIRPKG="$tmp/packages"
BOOTSTRAPCHROOT="$tmp/$subdir"

curlparams=""
# Display progress bar only if we are outputing to a tty
if [ -t 2 ]; then
    curlparams="$curlparams -#"
fi

# Try to download a file, at most 10 times (same as deboostrap)
curlretry() {
    try=0
    while [ $try -lt 10 ]; do
        try="$((try+1))"
        if curl $curlparams "$@"; then
            return 0
        fi
        ret=$?
        sleep 1
    done
    return "$ret"
}

mkdir -p "$FETCHDIRDB" "$FETCHDIRPKG" "$BOOTSTRAPCHROOT"

echo "Fetching repository packages list..." 1>&2
# Fetch Arch package database
for repo in $REPOS; do
    echo "Fetching $repo..." 1>&2
    mirrorbase="`echo "$MIRROR" | sed -e "s/\\$repo/$repo/" \
                                      -e "s/\\$arch/$ARCH/"`"
    curlretry -o "$FETCHDIRDB/$repo.db" "$mirrorbase/$repo.db" 1>&2
    # Create package list in this format: $repo:package-version
    tar tf "$FETCHDIRDB/$repo.db" \
        | sed -n 's|^\(.*\)/$|'"$repo"':\1|p' >> "$LIST"
done

# Get the value of a field in the Arch package database
# getdbfield repo pkgver [desc|depends] field
getdbfield() {
    local repo="$FETCHDIRDB/$1.db"
    local file="$2/$3"
    local field="$4"
    # Extract the relevant file
    tar xf "$repo" -O "$file" | awk '
        /^$/ { m = 0 }
        m { print }
        /^%'"$field"'%$/ { m = 1 }
    '
}

echo "Downloading and extracting packages..." 1>&2
# Final space critical for element extraction
missing="$PACKAGES_BOOTSTRAP "
installed=" "
bootstrappkg=""

# Install packages, taking care of dependencies:
# - Remove first package in $missing.
# - If package has not been installed already, install it, and record all
#   dependencies in $missing.
# - Loop until $missing is empty.

while [ -n "$missing" ]; do
    package="${missing%% *}"
    missing="${missing#$package }"

    # Do not install if already installed
    if [ "${installed#*" $package "}" != "$installed" ]; then
        continue
    fi

    echo "Downloading and installing $package..." 1>&2
    pkg="`grep -m 1 ":$package-[0-9]" "$LIST"`"
    if [ -z "$pkg" ]; then
        echo "Cannot find package $package..." 1>&2
        exit 1
    fi
    repo="${pkg%:*}"
    pkgver="${pkg#*:}"
    file="`getdbfield "$repo" "$pkgver" "desc" "FILENAME"`"
    mirrorbase="`echo "$MIRROR" | sed -e "s/\\$repo/$repo/" \
                                      -e "s/\\$arch/$ARCH/"`"
    curlretry -o "$FETCHDIRPKG/$file" "$mirrorbase/$file" 1>&2
    tar --warning=no-unknown-keyword -xkf "$FETCHDIRPKG/$file" \
        --exclude=".PKGINFO" --exclude=".MTREE" \
        --exclude=".INSTALL" --exclude=".Changelog" \
        -C "$BOOTSTRAPCHROOT"

    # Get list of dependencies (ignore versions)
    ndep="`getdbfield "$repo" "$pkgver" "depends" "DEPENDS" \
                     | sed -n 's/^\([^<>=]*\).*$/\1/p' | tr '\n' ' '`"

    # Some packages provide virtual packages (e.g. bash provides sh):
    # Add those to the installed list
    nprovides="`getdbfield "$repo" "$pkgver" "depends" "PROVIDES" \
                          | tr '\n' ' '`"

    bootstrappkg="$bootstrappkg $package"
    installed="$installed $nprovides $package "
    missing="$missing $ndep"
done

# Move databases to bootstrap fs
mkdir -p "$BOOTSTRAPCHROOT/var/lib/pacman/sync"
mv "$FETCHDIRDB"/*.db "$BOOTSTRAPCHROOT/var/lib/pacman/sync"
# Move package tarballs, so we can reinstall them properly
mkdir -p "$BOOTSTRAPCHROOT/var/cache/pacman/pkg"
mv "$FETCHDIRPKG"/* "$BOOTSTRAPCHROOT/var/cache/pacman/pkg"

echo "arch" > "$BOOTSTRAPCHROOT/etc/hostname"

# Make sure package architecture is set manually.
# Using the default Auto here detects the chroot from uname -m, breaking i686
# chroots on x86-64.
sed -i 's/^[ \t]*Architecture[ \t].*/Architecture = '"$ARCH"'/' \
    "$BOOTSTRAPCHROOT/etc/pacman.conf"

echo "$bootstrappkg" > "$BOOTSTRAPCHROOT"/crouton-bootstrap-pkg

