#!/bin/sh -e
# Copyright (c) 2014 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This is a distro-specific continuation of the prepare.sh script.

PKGEXT='tar.xz'
DISTROAKA='arch'

# aurcompile <package> <extra makepkg options>: compile package from AUR.
# This should not be a permanent solution, as AUR packages cannot be trusted,
# and may break. Ideally, we would like packages to be pushed to [community].
# We create the user 'aur' to compile the package, giving it sudo access, so
# that dependencies and the package itself can be installed automatically.
aurcompile() {
    local package="$1"
    shift
    echo "Compiling $package from AUR..." 1>&2
    # Make sure base-devel and wget are installed
    # Expand base-devel so that install can replace packages with their
    # multilib versions
    install --asdeps `pacman -Sg base-devel | cut -d' ' -f 2`

    if ! id aur > /dev/null 2>&1; then
        useradd aur -r -s /bin/false
    fi

    SUDOERSFILE="/etc/sudoers.d/99-aur-pacman"
    echo "aur ALL = NOPASSWD:/usr/bin/pacman" > "$SUDOERSFILE"
    addtrap "rm -f '$SUDOERSFILE'"

    su aur -s /bin/sh -c '
        set -e
        PACKAGE="'"$package"'"
        PACKAGE2="${PACKAGE%"${PACKAGE#??}"}"
        TMPDIR="`mktemp -d --tmpdir=/tmp crouton-aur.XXX`"
        TRAP="rm -rf '\''$TMPDIR'\''"
        trap "$TRAP" INT HUP TERM 0
        cd "$TMPDIR"
        wget "https://aur.archlinux.org/packages/$PACKAGE2/$PACKAGE/$PACKAGE.tar.gz"
        tar xf "$PACKAGE.tar.gz"
        cd "$PACKAGE"
        pkgver="`sed -n "s/^pkgver=//p" PKGBUILD`"
        pkgrel="`sed -n "s/^pkgrel=//p" PKGBUILD`"
        if pacman -Q "$PACKAGE" 2>/dev/null | \
                    grep "^$PACKAGE $pkgver-$pkgrel\$"; then
            echo "Package $PACKAGE already up to date ($pkgver-$pkgrel)."
        else
            makepkg -A -s -i '"$*"' --noconfirm
        fi
    '

    rm -f "$SUDOERSFILE"
    undotrap

    return 0
}

# Detect if multilib repositories are installed
arch_multilib() {
    pacman -Sl multilib >/dev/null 2>&1
}

# install_dist: see install() in prepare.sh for details.
# We ignore the second part of the parameters, as Arch only pulls required deps.
# We also replace gcc by its multilib version, if the multilib repository is
# enabled.
install_dist() {
    local pkgs='' aurpkgs='' params='' multilib=''
    if arch_multilib; then
        multilib='y'
    fi
    while [ "$#" != 0 ]; do
        if [ "$1" = "--minimal" ]; then
            : # Ignore: irrelevant for arch
        elif [ "$1" = "--asdeps" ]; then
            params="--asdeps"
        else
            break
        fi
        shift
    done
    while [ "$#" != 0 ]; do
        if [ "$1" = '--' ]; then
            shift
            break
        fi
        aurstrip="${1#aur:}"
        if [ "$aurstrip" = "$1" ]; then
            if [ -n "$multilib" -a "$1" = "gcc" ]; then
                pkgs="$pkgs $1-multilib"
            else
                pkgs="$pkgs $1"
            fi
        else
            aurpkgs="$aurpkgs $aurstrip"
        fi
        shift
    done
    if [ -n "$pkgs" ]; then
        pacman -S --noconfirm --needed $params $pkgs
    fi

    if [ -n "$aurpkgs" ]; then
        for aurpkg in $aurpkgs; do
            aurcompile $aurpkg $params
        done
    fi
}


# install_pkg_dist: see install_pkg() in prepare.sh for details.
install_pkg_dist() {
    error 1 'ERROR: install_pkg_dist is not supported on Arch'
}


# remove_dist: see remove() in prepare.sh for details.
remove_dist() {
    if [ "$#" -gt 0 ]; then
        pacman -R "$@"
    fi
}


# list_uninstalled_dist: see list_uninstalled() in prepare.sh for details.
list_uninstalled_dist() {
    local suffix="$1" pkg
    if [ -n "$suffix" ]; then
        error 1 'list_uninstalled_dist: suffix makes no sense on Arch'
    fi
    shift
    for pkg in "$@"; do
        if ! pacman -Q "$pkg" >/dev/null 2>&1; then
            echo -n "$pkg "
        fi
    done
}

# Run boostrap second stage if it hasn't already happened
bootstrappkglist="/crouton-bootstrap-pkg"
if [ -r "$bootstrappkglist" ]; then
    # This is technically not necessary, as we are not fetching anything at this
    # stage, but pacman complains if no mirror is set. We setup a dummy one,
    # to make sure we really do not fetch anything (we need to install the
    # exact same packages as during the bootstrap creation, to make sure we
    # do not leave any cruft behind).
    if [ -n "$MIRROR" -a "$MIRROR" != 'unspecified' ]; then
        echo "Server = https://192.0.2.1/" > "/etc/pacman.d/mirrorlist"
    fi

    # Initialize pacman keyring (i686/x86_64 only)
    if [ "${ARCH#arm}" = "$ARCH" ]; then
        cat 1>&2 <<END
Initializing pacman keyring...
If this gets stuck, generate entropy by moving the mouse around (e.g. do some
random browsing).
END
        pacman-key --init
        pacman-key --populate archlinux
    fi

    # Force overwritting packages files in the bootstrap, without any sort
    # of dependency checking: this makes sure package content are properly
    # recorded
    pacman -S --nodeps --nodeps --asdeps --noconfirm --force \
        `cat "$bootstrappkglist"`

    # Reset architecture
    sed -i 's/^[ \t]*Architecture[ \t].*/Architecture = '"$ARCH"'/' \
        /etc/pacman.conf

    # Restore the original /etc/resolv.conf
    if [ -f /etc/resolv.conf.pacorig ]; then
        rm -f /etc/resolv.conf
        mv -f /etc/resolv.conf.pacorig /etc/resolv.conf
    fi

    # Now install a proper set of base packages

    # Packages that are in base, but that we do not want to install in the
    # chroot (nothing prevents the user from installing them later on)
    PACKAGES_TARGET_IGNORE="cronie device-mapper dhcpcd heirloom-mailx \
    jfsutils logrotate lvm2 mdadm netctl pciutils reiserfsprogs \
    systemd-sysvcompat xfsprogs"

    # Only erase mirror if specified (in case pacman fails later on)
    if [ -n "$MIRROR" -a "$MIRROR" != 'unspecified' ]; then
        # Keep a reference of the existing mirrorlist
        mv /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.pacorig
        echo "Server = $MIRROR" > "/etc/pacman.d/mirrorlist"
    fi

    # Synchronize
    pacman -Sy

    # Build a reasonable set of base packages, using pacman's output as reference,
    # then remove packages in PACKAGES_TARGET_IGNORE.
    allbasepkg="`pacman -Sg base | cut -d' ' -f 2`"

    basepkg=""
    for PACKAGE in $allbasepkg; do
        inst='y'
        for IPKG in $PACKAGES_TARGET_IGNORE; do
            if [ "$IPKG" = "$PACKAGE" ]; then
                inst=
            fi
        done

        if [ -n "$inst" ]; then
            basepkg="$basepkg $PACKAGE"
        fi
    done

    echo "Installing these base packages:"
    echo "$basepkg"

    pacman --noconfirm --needed -S $basepkg

    # Make sure all these packages are marked as installed explicitly
    pacman -D --asexplicit $basepkg >/dev/null

    rm -f "$bootstrappkglist"

    # Request a script restart to refresh the mount environment and recreate
    # groups (/etc/group and other files were erased)
    relaunch_setup
fi

# Fix the keyboard mode early on (this will be called again after dist-upgrade).
fixkeyboardmode
