#!/bin/sh -e
# Copyright (c) 2016 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

NEWTABPAGE='chrome://newtab'
USAGE="${0##*/} [-n] [URL]
Open an URL in Chromium OS (requires crouton extension).
If no URL is specified, opens $NEWTABPAGE instead.
Switches back to Chromium OS unless -n is specified."

. "`dirname "$0"`/../installer/functions"

noswitch=''
if [ "$1" = '-n' ]; then
    noswitch='y'
    shift
fi

if [ -z "$*" ]; then
    set -- "$NEWTABPAGE"
elif [ "$1" = '-h' -o "$1" = '--help' ]; then
    error 0 "$USAGE"
fi

STATUS="`echo -n U"$*" | websocketcommand`"

if [ "$STATUS" != 'UOK' ]; then
    error 1 "${STATUS#?}"
fi

if [ -z "$noswitch" ]; then
    croutoncycle cros
fi
