#!/bin/sh -e
# Copyright (c) 2014 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This is a distro-specific continuation of the prepare.sh script.

# Run debootstrap second stage if it hasn't already happened
if [ -r /debootstrap ]; then
    # Debootstrap doesn't like anything mounted under /sys or /var when it
    # runs. We request a re-mount after bootstrapping, so these mounts will
    # be fixed. We also can't detect the mounts properly due to the chroot,
    # so we have to recursively find mountpoints under /sys, and hardcode
    # /var umounts.
    find /sys/* -maxdepth 2 -depth -type d \
         -exec mountpoint -q {} \; -exec umount {} \;
    umount '/var/run/lock' '/var/run'
    # Start the bootstrap
    /debootstrap/debootstrap --second-stage
    # Clean contents of /var/run (since we'll always be mounting over it).
    rm -rf --one-file-system /var/run/*
    # Request a script restart to refresh the mount environment
    relaunch_setup
else
    # Do any pending configuration, in case of an unfortunately-timed Ctrl-C
    dpkg --configure -a

    # Fix the keyboard mode in case it got reverted to raw
    fixkeyboardmode
fi

