#!/bin/sh -e
# Copyright (c) 2017 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This file is sourced from main.sh to update distro-specific defaults.
# It must set at least ARCH and MIRROR if not already specified.

if [ -z "$ARCH" ]; then
    ARCH="$(uname -m)"
fi

case "$ARCH" in
amd64 | x86_64) ARCH="amd64";;
x86 | i?86) ARCH="x86";;
armv7a_hardfloat | armv7hl) ARCH="armv7a_hardfloat";;
armv7a | armv7l) ARCH="armv7a";;
arm64 | aarch64) ARCH="arm64";;
*) error 2 "Invalid architecture '$ARCH'.";;
esac

# Set a default mirror
if [ -z "$MIRROR" ]; then
    MIRROR="${CROUTON_MIRROR_gentoo:-http://distfiles.gentoo.org/}"
fi
