#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# All supported releases should be able to create an audio chroot and play sound
for release in $SUPPORTED_RELEASES; do
    snapshot "$release" core
    crouton -u -n "$release" -t audio

    # We pass -fdat to aplay/arecord, which means 48kHz, 16-bit, stereo.
    # dd to writes/reads 8 blocks of 48000 bytes: 2 seconds worth of sound.
    exitswithin 0 5 host enter-chroot -n "$release" \
        sh -ec 'dd if=/dev/zero bs=48000 count=8 | aplay -fdat -v'
    exitswithin 0 5 host enter-chroot -n "$release" \
        sh -ec 'arecord -fdat -v | \
                dd of=/dev/null bs=48000 count=8 iflag=fullblock'
    host enter-chroot -n "$release" cras_test_client --dump_server_info

    # On x86_64 systems, test x86 client
    if [ "`uname -m`" = "x86_64" ]; then
        host enter-chroot -n "$release" \
            /usr/local/i386-linux-gnu/bin/cras_test_client --dump_server_info

        # Try to install i386 version of alsa-utils
        # Ignore errors: some distributions are broken (e.g. precise)
        # Also install "file" to detect the architecture
        if host enter-chroot -n "$release" -u 0 \
                apt-get -y --no-install-recommends install \
                    alsa-utils:i386 file; then
            # Confirm that aplay is indeed the i386 version
            passes host enter-chroot -n "$release" file /usr/bin/aplay | \
                tee /dev/stderr | passes grep -q "Intel 80386"
            exitswithin 0 5 host enter-chroot -n "$release" \
                sh -ec 'dd if=/dev/zero bs=48000 count=8 | aplay -fdat -v'
            exitswithin 0 5 host enter-chroot -n "$release" \
                sh -ec 'arecord -fdat -v | \
                        dd of=/dev/null bs=48000 count=8 iflag=fullblock'
            # Restore native alsa-utils
            host enter-chroot -n "$release" -u 0 \
                apt-get -y --no-install-recommends install alsa-utils
        else
            echo "Cannot install alsa-utils:i386 in $release (not fatal)." 2>&1
        fi
    fi

    host enter-chroot -n "$release" -u 0 \
        apt-get -y --no-install-recommends install pulseaudio pulseaudio-utils
    exitswithin 0 10 host enter-chroot -n "$release" sh -exc '
        pulseaudio --start
        echo | pacat -v
        dd if=/dev/zero bs=48000 count=8 | aplay -f dat -Dpulse -v
        arecord -fdat -Dpulse -v | \
            dd if=/dev/null bs=48000 count=8 iflag=fullblock
        cras_test_client --dump_server_info
        pulseaudio --kill
        '
    host delete-chroot -y "$release"
done
