#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# All supported releases should be able to create an audio chroot and play sound
for release in $SUPPORTED_RELEASES; do
    snapshot "$release" core
    crouton -u -n "$release" -t audio

    # We pass -fdat to aplay/arecord, which means 48kHz, 16-bit, stereo.
    # dd writes/reads 8 blocks of 48000 bytes: 2 seconds worth of sound.
    host enter-chroot -n "$release" sh -exc '
        cras_test_client --dump_server_info
        dd if=/dev/zero bs=48000 count=8 | aplay -fdat -v
        arecord -fdat -v | dd of=/dev/null bs=48000 count=8 iflag=fullblock
        '

    # On x86_64 systems, test x86 client
    if [ "`uname -m`" = "x86_64" ]; then
        host enter-chroot -n "$release" sh -exc '
            /usr/local/i386-linux-gnu/bin/cras_test_client --dump_server_info
            apt-get download alsa-utils:i386
            dpkg -x alsa-utils_*_i386.deb .
            dd if=/dev/zero bs=48000 count=8 | ./usr/bin/aplay -fdat -v
            ./usr/bin/arecord -fdat -v | \
                        dd of=/dev/null bs=48000 count=8 iflag=fullblock
            '
    fi

    host enter-chroot -n "$release" -u 0 \
        apt-get -y --no-install-recommends install pulseaudio pulseaudio-utils
    host enter-chroot -n "$release" sh -exc '
        pulseaudio --start
        echo | pacat -v
        dd if=/dev/zero bs=48000 count=8 | aplay -f dat -Dpulse -v
        arecord -fdat -Dpulse -v | \
            dd if=/dev/null bs=48000 count=8 iflag=fullblock
        cras_test_client --dump_server_info
        pulseaudio --kill
        '
    host delete-chroot -y "$release"
done
