#!/bin/sh -eu
# Copyright (c) 2014 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# All supported releases should be able to create a core chroot and enter it.
for release in $SUPPORTED_RELEASES; do
    crouton -r "$release" -t core
    host enter-chroot -n "$release" true
    host delete-chroot -y "$release"
done
