#!/bin/sh -e
# Copyright (c) 2015 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# All supported releases should be able to create a core chroot and enter it.

if [ -z "$release" ]; then
    echo "all"
    exit 0
fi

crouton -r "$release" -t core
host enter-chroot -n "$release" true
host delete-chroot -y "$release"
