#!/bin/sh -e
# Copyright (c) 2015 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# All supported releases should be able to create an i686 chroot on x86-64

if [ -z "$release" ]; then
    if [ "`uname -m`" = "x86_64" ]; then
        echo "all"
    fi
    exit 0
fi

crouton -a x86 -r "$release" -t core
host enter-chroot -n "$release" true
host delete-chroot -y "$release"
