#!/bin/sh -e
# Copyright (c) 2014 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Check that current kernels are verified, if we are running an official image
if grep '^CHROMEOS_RELEASE_NAME=Chrome OS$' /etc/lsb-release; then
    passes from 'installer/main.sh' import verifykernelsig
    passes verifykernelsig
else
    log "Non-official image: skipping kernel verification test."
fi
