#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# xorg won't work on arm
if uname -m | grep -q 'arm'; then
    log "xorg is not available on ARM. Skipping test."
    exit 0
fi

# All supported releases should be able to launch an xorg server
for release in $SUPPORTED_RELEASES; do
    snapshot "$release" audio
    crouton -U -n "$release" -t xorg
    vtlock exitswithin 0 60 host \
        enter-chroot -n "$release" exec xinit /usr/bin/xterm -e exit 0
    host delete-chroot -y "$release"
done
