#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

for release in $SUPPORTED_RELEASES; do
    crouton -r "$release" -t cli-extra
    # This should not pull in any target (neither core nor cli-extra)
    echo '
        echo "Custom target ($RELEASE, $DISTRO, $DISTROAKA)"
    ' | crouton -T -U -r "$release" | log
    # This should update cli-extra+core
    crouton -r "$release" -u
done
