#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Reloads the daemon running the tester, if one exists, by killing it.
pid="$$"
while ps -p "$pid" -ocmd= | grep -q "$0"; do
    pid="`ps -p "$pid" -oppid=`"
done
kill "$pid"
