#!/bin/sh -e
# Copyright (c) 2014 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This test is sourced by other w* test, do not run it on it's own
if [ -z "$release" -o -z "$target" ]; then
    exit 0
fi

if [ -z "$startcmd" ]; then
    error 2 "startcmd not defined"
fi

# Start with a x11 snapshot
snapshot "$release" x11

# Install snapshot tools + xte
echo 'install --minimal x11-apps imagemagick xautomation' | \
    crouton -T -U -n "$release"

ret=0
crouton -u -n "$release" -t "$target" || ret=$?
if [ "$ret" -ne 0 ]; then
    if [ "$ret" -eq 99 ]; then
        log "Target $target failed on $release, as expected (unsupported combination)."
        exit 0
    else
        log "Target $target failed on $release."
        exit "$ret"
    fi
fi

(
    vtlock
    host "$startcmd" -b -n "$release"
    # FIXME: Wait for croutoncycle to change?
    sleep 60
    host enter-chroot -n "$release" sh -exc '
        # Test croutoncycle as a bonus
        export DISPLAY="`croutoncycle display`"
        if [ "$DISPLAY" = ":0" -o "$DISPLAY" = "aura" ]; then
            echo "Invalid display ($DISPLAY)." 1>&2
            exit 1
        fi
        if [ -n "'"$xte"'" ]; then
            echo "'"$xte"'" | tr ";" "\n" | xte
            sleep 60
        fi
        # Snapshot!
        xwd -root | convert -quality 75 xwd:- ~/"screenshot-'"$target"'.jpg"'

    mv "$PREFIX/chroots/$release/home/test/screenshot-$target.jpg" \
        "$file-snapshot.jpg"

    host unmount-chroot -f -y "$release"
)

host delete-chroot -y "$release"
