#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

set -e

# defines the usage of the program.
usage="
Name:             backup-chroot.

Description:      Needs root access for everything but displaying this message.
                  backup-chroot will by default create:
                  ~/Downloads/crouton-backups/name/name-yyyymmdd-hhmm.tar.gz.  
    
Usage:            backup-chroot <options> name

Options:
    -h or --help  This will show this message as well as calling backup-chroot.
    -t target     This will set the target to something other than the default.
                  Do not add a trailing slash at the end of this parameter.

    -f filename   This will change the filename, setting a pure .tar will force
                  the program not to use compression. You can also force
                  other compression algorithms.
                  
Examples:         sudo backup-chroot
                  sudo backup-chroot sid
                  sudo backup-chroot -t ~/Downloads -f sid.tar.gz sid"
          
## setting defaults
default_target="/home/chronos/user/Downloads/crouton-backups"
date="`date '+%Y%m%d-%H%M'`"

## This if loop sets the initial parameters of what is allowed in this command.
if [ ! "$1" = '' ] && [ "$2" = '' ] || [ "$1" = '-t' ] || [ "$1" = '-f' ] && 
    [ "$3" = '-t' ] || [ "$3" = '-f' ] || [ "$3" = '' ] && [ "$6" = '' ]; then
  for i in $@  ## This for loop sets parameters of the target directory and filename.
  do
  if [ ! "$i" = '' ] && ## This means that $name will be the only entry and to automate the backup.
     [ ! "$target" = 'y' ] || [ ! "$i" = '-t' ] && 
     [ ! "$filename" = 'y' ] || [ ! "$i" = '-f' ]; then
    name="$i"
    filename="$name-$date.tar.gz"
    target="$default_target"/"$name"
  elif [ "$filename" = 'y' ]; then ## This sets the filename.
    filename="$i"
    if [ ! "$target" = 'y']; then ## This sets the target only if the user did not select one.
      target="$default_target"/"$name" 
    fi
  elif [ "$target" = 'y' ]; then ## This sets the target.
    target="$i"
    if [ ! "$filename" = 'y' ]; then ## This sets the filename only if the user did not select one.
      filename="$name-$date.tar.gz"
    fi
  elif [ "$i" = '-f' ]; then ## redirects to set the filename on the next pass.
    filename='y'
  elif [ "$i" = '-t' ]; then ## redirects to set the target on the next pass.
    target='y'
  else
   echo "$usage"
   exit 0
  fi
done
else
  echo "$usage"
  exit 0
fi
if [ ! $filename = '' ] || [ ! $target = '' ] || [ ! $name = '' ]; then
  mkdir -p "$target" # create the target
  edit-chroot -f "$target"/"$filename" -b "$name" #backup the chroot.
  exit 0
else
 echo "$usage
 
 You entered a blank or invalid name, Target directory or filename."
 exit 0
fi
