#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# created by Edward Tunnah aka edge226.

set -e

# defines the usage of the program.
usage="
Name:             backup-chroot.

Description:      Needs root access for everything but displaying this message.
                  backup-chroot will by default create:
                  ~/Downloads/crouton-backups/name/name-yyyymmdd-hhmm.tar.gz.  
    
Usage:            backup-chroot <options> name

Options:
    -h or --help  This will show this message as well as calling backup-chroot.
    -t target     This will set the target to something other than the default.
                  Do not add a trailing slash at the end of this parameter.

    -f filename   This will change the filename, setting a pure .tar will force
                  the program not to use compression. You can also force
                  other compression algorithms.
                  
Examples:         sudo backup-chroot
                  sudo backup-chroot sid
                  sudo backup-chroot -t ~/Downloads -f sid.tar.gz sid"
          
# setting defaults
default_target="/home/chronos/user/Downloads/crouton-backups"
date="`date '+%Y%m%d-%H%M'`"
if [ ! "$1" = '' ] && [ "$2" = '' ] || [ "$1" = '-t' ] || [ "$1" = '-f' ] && 
    [ "$3" = '-t' ] || [ "$3" = '-f' ] || [ "$3" = '' ] && [ "$6" = '' ]; then
  for i in $@
  do
  if [ ! "$i" = '' ] && 
     [ ! "$target" = 'y' ] || [ ! "$i" = '-t' ] && 
     [ ! "$filename" = 'y' ] || [ ! "$i" = '-f' ]; then
    name="$i"
    filename="$name-$date.tar.gz"
    target="$default_target"/"$name"
  elif [ "$filename" = 'y' ]; then
    filename="$i"
    if [ ! "$target" = 'y']
      target="$default_target"/"$name"
    fi
  elif [ "$target" = 'y' ]; then
    target="$i"
    if [ ! "$filename" = 'y' ]; then
      filename="$name-$date.tar.gz"
    fi
  elif [ "$i" = '-f' ]; then
    filename='y'
  elif [ "$i" = '-t' ]; then
    target='y'
  else
   echo "$usage"
   exit 0
  fi
done
else
  echo "$usage"
fi
if [ ! $filename = '' ] || [ ! $target = '' ] || [ ! $name = '' ]; then
  mkdir -p "$target" # create the target
  edit-chroot -f "$target"/"$filename" -b "$name" #backup the chroot.
  exit 0
else
 echo "$usage
 
 You entered a blank or invalid name, Target directory or filename."
 exit 0
fi
