#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# created by Edward Tunnah aka edge226.

set -e

# defines the usage of the program.
usage="
Name:             backup-chroot.

Description:      Needs root access for everything but displaying this message.
                  backup-chroot will by default create:
                  ~/Downloads/crouton-backups/name/name-yyyymmdd-hhmm.tar.gz.  
    
Usage:            backup-chroot <options> name

Options:
    -h or --help  This will show this message as well as calling backup-chroot.
    -t target     This will set the target to something other than the default.
                  Do not add a trailing slash at the end of this parameter.

    -f filename   This will change the filename, setting a pure .tar will force
                  the program not to use compression. You can also force
                  other compression algorithms.
                  
Examples:         sudo backup-chroot
                  sudo backup-chroot sid
                  sudo backup-chroot -t ~/Downloads -f sid.tar.gz sid"
          
# setting defaults
default_target="/home/chronos/user/Downloads/crouton-backups"
date="`date '+%Y%m%d-%H%M'`"
for i in $@
  do
  if [ "$filename" = 'y' ]; then
    filename="$i-$date.tar.gz"
  elif [ "$target" = 'y' ]; then
    target="$i"
  elif [ "$i" = '-f' ]; then
    echo "-f iteration"
    filename='y'
  elif [ "$i" = '-t' ]; then
    echo "-t iteration"
    target='y'
  elif [ ! "$i" = '' ]; then
    echo "name iteration"
    name="$i"
  elif [ "$2" = '' ]; then
  filename="$name-$date.tar.gz"
  target="$default_target"
  else
    echo "$usage"
    exit 0
  fi
done
mkdir -p "$target" # create the target
edit-chroot -f "$target"/"$filename" -b "$name"
exit 0
