#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# created by Edward Tunnah aka edge226.

set -e

for f in $@
  do
  n=$((f+1))
  echo "f = $f"
  echo "n = $n"
done
