#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# created by Edward Tunnah aka edge226.

set -e
next=''
for i in $@
  do
  if [ "$i" = '-f' ]; then
  next='y'
  fi
  if [ "$next" = 'y' ]; then
    echo "$i"
    next=''
  fi
  echo "i = $i"
done
