#!/bin/sh -e
# Copyright (c) 2014 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

logfile="/tmp/Xorg.crouton.$$.log"
for arg in "$@"; do
    disp="`echo "$arg" | sed -n 's/^\:\([0-9]*\)$/\1/p'`"
    if [ -n "$disp" ]; then
        logfile="/tmp/Xorg.crouton.$disp.log"
    fi
done

export XMETHOD='xiwi'
XARGS="-nolisten tcp -config xorg-dummy.conf -logfile $logfile"
if [ -f /etc/crouton/xserverrc-local ]; then
    . /etc/crouton/xserverrc-local
fi

# Find the Xorg executable (first 2 required by Arch, third by Debian/Ubuntu)
XBINS="/usr/lib/xorg-server/Xorg /usr/bin/Xorg.bin /usr/bin/Xorg"
XBIN=""
for xbin in $XBINS; do
    if [ -x "$xbin" ] && ! [ -u "$xbin" -o -g "$xbin" ]; then
        XBIN="$xbin"
        break
    fi
done

if [ -z "$XBIN" ]; then
    echo "Cannot find non-setuid Xorg executable." 1>&2
    exit 1
fi

exec "$XBIN" $XARGS "$@"
