#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# Launch unity-panel-service and any indicators in /usr/share/upstart/sessions.

# Get RELEASE from croutonversion.
croutonversion='/usr/local/bin/croutonversion'
RELEASE='unknown'
if [ -f "$croutonversion" ]; then
    RELEASE="`$croutonversion -r`"
fi

# Both saucy and trusty need to launch unity-panel-service.
if [ "$RELEASE" = 'saucy' -o "$RELEASE" = 'trusty' ]; then
    /usr/lib/unity/unity-panel-service >/dev/null 2>&1 &
fi

# If on trusty, indicators also need to be started.
if [ "$RELEASE" = 'trusty' ]; then
    for f in /usr/share/upstart/sessions/*.conf; do
        if grep -q '^start on .*indicator-services-start.*' "$f"; then
            # Parse out exec and launch.
            # Assume no space in path, and run without args.
            exec_cmd="`awk '/^exec/{print $2; exit}' "$f"`"
            "$exec_cmd" >/dev/null 2>&1 &
        fi
    done
fi
