#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

export DISPLAY=':0' XAUTHORITY='/var/host/Xauthority'

XMETHOD='xephyr'
XARGS='-fullscreen -host-cursor -nolisten tcp'
if [ -f /etc/crouton/xserverrc-local ]; then
    . /etc/crouton/xserverrc-local
fi

exec /usr/bin/Xephyr $XARGS "$@"
