#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Disable framebuffer compression when displaying natively.
# For haswell it can stay enabled if 20-intel-crouton.conf exists.
# This xorg config file enables sna accelaration and set TearFree to true
# to support fbc.

fbc='/sys/module/i915/parameters/i915_enable_fbc'
if [ -w "$fbc" ] && [ ! -L "/usr/share/X11/xorg.conf.d/20-intel-crouton.conf" ]; then
    echo 0 > "$fbc"
fi

XMETHOD='x11'
XARGS='-nolisten tcp'
if [ -f /etc/crouton/xserverrc-local ]; then
    . /etc/crouton/xserverrc-local
fi

exec /usr/bin/X $XARGS "$@"
