#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

XMETHOD='x11'
XARGS='-nolisten tcp'
if [ -f /etc/crouton/xserverrc-local ]; then
    . /etc/crouton/xserverrc-local
fi

exec /usr/bin/X $XARGS "$@"
