#!/bin/sh -e
# Copyright (c) 2014 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

export XMETHOD='xorg'
XARGS='-nolisten tcp'
if [ -f /etc/crouton/xserverrc-local ]; then
    . /etc/crouton/xserverrc-local
fi

X=/usr/bin/X

# Freon needs the preload hack for X to coexist
if [ ! -f "/sys/class/tty/tty0/active" ]; then
    X=/usr/bin/Xorg
    XARGS="-logfile /tmp/Xorg.$$.log $XARGS"
    export LD_PRELOAD="/usr/local/lib/croutonfreon.so:$LD_PRELOAD"
fi

exec "$X" $XARGS "$@"
