#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
if [ "${TARGETNOINSTALL:-c}" = 'c' ] &&
       [ "${DISTROAKA:-"$DISTRO"}" = 'arch' ]; then
    error 99 "lxde-desktop target is not supported on arch."
fi
REQUIRES='lxde'
DESCRIPTION='Installs LXDE along with common applications. (Approx. 800MB)'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
install ubuntu=lubuntu-desktop,task-lxde-desktop -- network-manager
