#!/bin/sh -e
# Copyright (c) 2014 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='gtk-extra'
DESCRIPTION='Installs the mate desktop environment. (Approx. 250MB)'
HOSTBIN='startmate'
CHROOTBIN='crouton-noroot startmate'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
# Ubuntu 12.04 has an old version of mate, but there's a PPA for mate 4.10.
if release -eq precise && [ "$ARCH" = 'amd64' -o "$ARCH" = 'i386' ]; then
    # Pull in the signing key
    apt-key adv --keyserver 'keyserver.ubuntu.com' \
                --recv-keys '07D44A5424C7C12A4BAB1E80EB563F93142986CE'
    # Add the software source
    cat > '/etc/apt/sources.list.d/mate-4.10.list' <<EOF
# Bring in mate 4.10 on Ubuntu 12.04
deb http://ppa.launchpad.net/xubuntu-dev/mate-4.10/ubuntu $RELEASE main
deb-src http://ppa.launchpad.net/xubuntu-dev/mate-4.10/ubuntu $RELEASE main
EOF
    # Update database
    apt-get update
fi

if [ "${DISTROAKA:-"$DISTRO"}" = 'debian' ]; then
    # Fix icons by setting default icon theme to Tango
    xfconfdir='/etc/skel/.config/mate/xfconf/mate-perchannel-xml'
    mkdir -p "$xfconfdir"
    cat > "$xfconfdir/xsettings.xml" <<EOF
<?xml version="1.0" encoding="UTF-8"?>

<channel name="xsettings" version="1.0">
  <property name="Net" type="empty">
    <property name="IconThemeName" type="string" value="Tango"/>
  </property>
</channel>
EOF
fi

install mate mate-goodies ubuntu=shimmer-themes, \
        -- dictionaries-common hddtemp xorg

TIPS="$TIPS
You can start mate via the startmate host command: sudo startmate
"
