#!/bin/sh -e
# Copyright (c) 2017 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This isn't a real target; it's the common commands for installing the various
# channels of the Google Chrome browser that the relevant targets source.

# This command expects CHANNEL to be set with the requested Google Chrome
# channel: stable, beta, or unstable.

if [ "${TARGETNOINSTALL:-c}" = 'c' -a "${ARCH#arm}" != "$ARCH" ]; then
    echo 'Google Chrome does not yet have an ARM build. Installing Chromium instead.' 1>&2
    TARGET=chromium
    . "${TARGETSDIR:="$PWD"}/$TARGET"
fi
if [ "${TARGETNOINSTALL:-c}" = 'c' ] && release -lt saucy -lt jessie; then
    echo "Google Chrome is not supported on $RELEASE anymore. Installing Chromium instead." 1>&2
    TARGET=chromium
    . "${TARGETSDIR:="$PWD"}/$TARGET"
fi
if [ "${TARGETNOINSTALL:-c}" = 'c' -a "$TARGET" != 'chrome' ]; then
    # Avoid installing multiple chrome targets
    if grep -q "^chrome\$" "${TARGETDEDUPFILE:-/dev/null}"; then
        exit
    else
        echo "chrome" >> "${TARGETDEDUPFILE:-/dev/null}"
    fi
fi
REQUIRES='x11'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
pkg="google-chrome-$CHANNEL"

# Chrome needs hicolor-icon-theme to configure/install
install hicolor-icon-theme

# Use the package manager for gentoo, it maintains chrome as well
if [ "${DISTROAKA:-"$DISTRO"}" = 'gentoo' ]; then
    # Rename google-chrome-stable to google chrome to match the ebuild
    if [ "$CHANNEL" = 'stable' ]; then
        GENTOO_PKG="www-client/google-chrome"
    else
        GENTOO_PKG="www-client/$pkg"
    fi

    # Keyword Chrome
    keyword_package "$GENTOO_PKG" "$pkg"

    # Accept the license
    accept_license "$GENTOO_PKG" google-chrome "$pkg"

    # Install chrome
    install "$GENTOO_PKG"

    # Install recommended fonts
    install media-fonts/arphicfonts media-fonts/bitstream-cyberbit \
        media-fonts/droid media-fonts/ipamonafont media-fonts/ja-ipafonts \
        media-fonts/takao-fonts media-fonts/wqy-microhei \
        media-fonts/wqy-zenhei
else
    # Only download if it's not already installed, since it auto-updates
    if [ -n "`list_uninstalled '' "$pkg"`" ]; then
        url="https://dl.google.com/linux/direct/${pkg}_current_$ARCH.$PKGEXT"
        tmp="`mktemp crouton.XXXXXX --tmpdir=/tmp`"
        addtrap "rm -f '$tmp'"

        wget "$url" -O "$tmp"

        # Remove other providers of google-chrome, then install the package
        for c in stable beta dev; do
            c="google-chrome-$c"
            if [ -z "`list_uninstalled '' "$c"`" ]; then
                remove "$c"
            fi
        done
        install_pkg "$tmp"
    else
        echo "$pkg is already installed."
    fi
fi
