#!/bin/sh -e
# Copyright (c) 2016 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
DESCRIPTION='Chromium is an open-source browser, stable channel.'
. "${TARGETSDIR:="$PWD"}/chromium-common"

### Append to prepare.sh:
CHANNEL='stable'
### append chromium-common
