#!/bin/sh -e
# Copyright (c) 2016 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
DESCRIPTION='Google Chrome browser, dev channel.'
. "${TARGETSDIR:="$PWD"}/chrome-common"

### Append to prepare.sh:
CHANNEL='unstable'
### append chrome-common
