#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='x11 core'
DESCRIPTION='Google Chrome browser, dev. Replaces Chromium if specified first.'
# Prevent Chromium from being added if it hasn't already.
echo 'chromium' >> "${TARGETDEDUPFILE:-/dev/null}"
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
CHANNEL='unstable'
### append chrome-common
