#!/bin/sh -eu
# Copyright (c) 2014 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='x11'
DESCRIPTION="Chromium browser. Uses the distro's version, which may be old."
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
install chromium-browser
