#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
if [ ! "$TARGETS" = 'help' ]; then
    if [ ! "$ARCH" = 'amd64' -a ! "$ARCH" = 'i386' ] &&
            ! release -gt quantal; then
        error 1 "cinnamon target not available on $RELEASE on $ARCH."
    elif release -le jessie; then
        error 1 "cinnamon target not available on $RELEASE."
    fi
fi
REQUIRES='gtk-extra'
DESCRIPTION='Installs the Cinnamon desktop environment. (Approx. 300MB)'
HOSTBIN='startcinnamon'
CHROOTBIN='startcinnamon gnome-session-wrapper'
CHROOTETC='nm-applet.desktop'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
if [ "$DISTRO" = 'ubuntu' ]; then
    # Ubuntu on i386/amd64 can use a PPA for the latest stable Cinnamon
    if [ "$ARCH" = 'amd64' -o "$ARCH" = 'i386' ]; then
        # Pull in the signing key
        apt-key adv --keyserver 'keyserver.ubuntu.com' \
                    --recv-keys '109C2938F84496D6ACB6D805A777609328949509'
        # Add the software source
        cat > '/etc/apt/sources.list.d/cinnamon-stable.list' <<EOF
# Cinnamon stable PPA
deb http://ppa.launchpad.net/gwendal-lebihan-dev/cinnamon-stable/ubuntu $RELEASE main
deb-src http://ppa.launchpad.net/gwendal-lebihan-dev/cinnamon-stable/ubuntu $RELEASE main
EOF
        # Update database
        apt-get update
        install --minimal ubuntu~precise=,cinnamon-control-center \
                cinnamon-screensaver nemo
    fi
fi

# Dummy nm-applet.desktop to allow cinnamon-session to start
mkdir -p /usr/local/share/applications
ln -sfT /etc/crouton/nm-applet.desktop \
        /usr/local/share/applications/nm-applet.desktop

install --minimal cinnamon \
        ubuntu~precise+ubuntu~quantal=,ubuntu~raring=nautilus,nemo \
        ubuntu~precise=gir1.2-gjsdbus-1.0, \
        ubuntu=gnome-icon-theme-full,debian=gnome-icon-theme, \
        gnome-themes-standard gnome-session gvfs-backends muffin python-cairo

TIPS="$TIPS
You can start Cinnamon via the startcinnamon host command: sudo startcinnamon
"
