#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='core'
DESCRIPTION='Basic CLI tools such as wget and ssh.'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
install wget openssh-client
