#!/bin/sh -e
# Copyright (c) 2016 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='core'
DESCRIPTION='Basic CLI tools such as ssh.'
HOSTBIN='startcli'
CHROOTBIN='croutonpowerd'
. "${TARGETSDIR:="$PWD"}/common"

# Set the use flags on gentoo that we'll need
if [ "${DISTROAKA:-"$DISTRO"}" = 'gentoo' ]; then
    set_flags dbus
fi

### Append to prepare.sh:
install dbus gentoo=openssh,openssh-client kbd

TIPS="$TIPS
You can start a shell in a new VT via the startcli host command: sudo startcli
"
