#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='x11'
DESCRIPTION='Installs cmt binaries from Chromium OS host as touchpad driver.'
CHROOTBIN='croutonwheel croutonwheel-autostart'
CHROOTETC='croutonwheel.desktop cmt-xorg.conf'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:

# provides xte for croutonwheel
install xautomation

# chroot /etc/crouton/cmt symlink activates cmt functionality
CHROMIUM_CMT=/var/host/cmt
CROUTON_ETC=/etc/crouton
ln -sf $CHROMIUM_CMT $CROUTON_ETC

# deploy croutonwheel.desktop symlink to start croutonwheel when X starts
mkdir -p /etc/xdg/autostart
ln -sf $CROUTON_ETC/croutonwheel.desktop /etc/xdg/autostart/croutonwheel.desktop

# for trusty, bypass the ABI mismatch error
ln -sf $CROUTON_ETC/cmt-xorg.conf /etc/X11/xorg.conf
