#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='x11'
DESCRIPTION='Installs cmt binaries from Chromium OS host as touchpad driver.'
CHROOTBIN='croutonwheel'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
install xautomation

CROUTON_CMT=/var/host/cmt
mkdir -p /etc/X11/xorg.conf.d
cd $CROUTON_CMT
cp -d lib/* /usr/lib
cp -d input/* /usr/lib/xorg/modules/input
cp -d xorg.conf.d/* /etc/X11/xorg.conf.d
