#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='x11'
DESCRIPTION='Chromium OS extension and crouton helper (clipboard synchronization and URL handling).'
CHROOTBIN='croutonclip croutonurlhandler'

if [ ! "$TARGETS" = 'help' ] && [ ! "$TARGETS" = 'check' ]; then
  # Chromium does not like to run as root
  su -c "${SCRIPTDIR:-..}/host-ext/gencrx.sh" chronos >&2
  cp "${SCRIPTDIR:-..}/host-ext/crouton.crx" /home/chronos/user/Downloads/
fi

. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
compile websocket ''

if [ "$XMETHOD" = 'x11' ]; then
    compile vtmonitor ''
fi

TIPS="$TIPS
For the best crouton \"experience\" (clipboard synchronization and URL
handling), you need to install crouton extension in Chromium OS:
Open the file manager, and click on Downloads/crouton.crx .
"
