#!/bin/sh -e
# Copyright (c) 2017 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
if [ "${TARGETNOINSTALL:-c}" = 'c' ] && release -lt jessie -eq kali; then
    error 99 "e17 target is not supported on wheezy/kali."
fi
REQUIRES='gtk-extra'
DESCRIPTION='Installs the enlightenment desktop environment. (Approx. 50MB)'
HOSTBIN='starte17'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
if [ "${DISTROAKA:-"$DISTRO"}" = 'gentoo' ]; then
    set_flags xrandr xcomposite
fi
install gentoo=enlightenment,e17

TIPS="$TIPS
You can start e17 via the starte17 host command: sudo starte17
"
