#!/bin/sh -e
# Copyright (c) 2016 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

if [ "${TARGETNOINSTALL:-c}" = 'c' ]; then
    if [ "$DISTRO" != 'ubuntu' ]; then
        error 99 "elementary target is only supported on Ubuntu."
    elif ! release -eq precise -o release -eq trusty -o release -eq xenial -o \
         release -eq yakkety -o release -eq zesty; then
        error 99 "elementary desktop is not available on this release."
    fi
fi

REQUIRES='x11'
DESCRIPTION='Installs the ELEMENTARY desktop environment. (Approx. 700MB)'
HOSTBIN='startelementary'
CHROOTBIN='crouton-noroot startelementary gnome-session-wrapper'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
apt-key adv --keyserver 'keyserver.ubuntu.com' \
            --recv-keys '4E1F8A59'

# Stable branch only available for LTS releases
# Expiremental daily branch available for other releases
if release -eq precise -o release -eq trusty -o release -eq xenial; then
  cat > '/etc/apt/sources.list.d/elementary-os.list' <<EOF
deb http://ppa.launchpad.net/elementary-os/os-patches/ubuntu $RELEASE main
deb-src http://ppa.launchpad.net/elementary-os/os-patches/ubuntu $RELEASE main
deb http://ppa.launchpad.net/elementary-os/stable/ubuntu $RELEASE main
deb-src http://ppa.launchpad.net/elementary-os/stable/ubuntu $RELEASE main
EOF
else
  cat > '/etc/apt/sources.list.d/elementary-os.list' <<EOF
deb http://ppa.launchpad.net/elementary-os/os-patches/ubuntu $RELEASE main
deb-src http://ppa.launchpad.net/elementary-os/os-patches/ubuntu $RELEASE main
deb http://ppa.launchpad.net/elementary-os/daily/ubuntu $RELEASE main
deb-src http://ppa.launchpad.net/elementary-os/daily/ubuntu $RELEASE main
EOF
fi

apt-get -y update
install pantheon elementary-wallpapers elementary-icon-theme \
        elementary-artwork elementary-default-settings \
        switchboard switchboard-gnome-control-center switchboard-plug-about \
        switchboard-plug-display switchboard-plug-pantheon-shell \
        switchboard-plug-gcc-date switchboard-plug-gcc-users \
        switchboard-gnome-control-center-override


TIPS="$TIPS
You can start Elementary OS via the startelementary host command: sudo startelementary
"
