#!/bin/sh -e
# Copyright (c) 2014 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='x11'
DESCRIPTION='Clipboard synchronization and URL handling with Chromium OS.'
CHROOTBIN='croutonclip croutonurlhandler'
EXTENSION='gcpneefbbnfalgjniomfjknbcgkbijom'

# Check if the extension is installed and add a mark to the preparation script
if [ -z "$TARGETNOINSTALL" ]; then
    if [ -d "/home/chronos/user/Extensions/$EXTENSION" ]; then
        echo 'EXTENSION_INSTALLED=y'
    else
        echo 'EXTENSION_INSTALLED=n'
    fi
fi

. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
install arch=xorg-utils,x11-utils xclip

compile websocket ''

# XMETHOD is defined in x11 (or xephyr), which this package depends on
if [ "$XMETHOD" = 'x11' ]; then
    compile vtmonitor ''
fi

# Use croutonurlhandler as a fallback URL handler
if [ "${DISTROAKA:-"$DISTRO"}" = 'debian' ]; then
    handler='/usr/local/bin/croutonurlhandler'
    for link in x-www-browser gnome-www-browser; do
        if ! update-alternatives --query "$link" | grep -q "$handler"; then
            update-alternatives --install "/usr/bin/$link" "$link" "$handler" 15
        fi
    done
elif [ "${DISTROAKA:-"$DISTRO"}" = 'arch' ]; then
    install arch=desktop-file-utils,

    cat > '/usr/local/share/applications/crouton.desktop' <<END
[Desktop Entry]
Encoding=UTF-8
Type=Application
Name=Crouton URL handler
GenericName=Web Browser
Comment=Open URL in Chromium OS via crouton extension
Exec=/usr/local/bin/croutonurlhandler %U
Icon=crouton
Terminal=false
StartupNotify=false
Categories=Application;Network;
MimeType=text/html;application/xhtml+xml;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/geo;
END

    update-desktop-database -q
fi

if [ "$EXTENSION_INSTALLED" = 'y' ]; then
    TIPS="$TIPS
You already have the Chromium OS extension installed, so you're good to go!
"
else
    TIPS="$TIPS
You must install the Chromium OS extension for integration with crouton to work.
The extension is available here: https://goo.gl/OVQOEt
"
fi
