#!/bin/sh -e
# Copyright (c) 2014 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='gtk-extra'
DESCRIPTION='Installs the GNOME desktop environment. (Approx. 400MB)'
HOSTBIN='startgnome'
CHROOTBIN='crouton-noroot startgnome gnome-session-wrapper'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
install --minimal evolution-data-server gnome-control-center \
        gnome-screensaver gnome-session gnome-session-fallback \
        gnome-shell gnome-themes-standard gvfs-backends nautilus \
        unzip gtk2-engines-pixbuf

TIPS="$TIPS
You can start GNOME via the startgnome host command: sudo startgnome
"
