#!/bin/sh -e
# Copyright (c) 2016 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='x11'
DESCRIPTION='GTK-based tools including gdebi, gksu, and a simple browser.'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
install_dummy network-manager network-manager-gnome
install gdebi gksu netsurf-gtk

# Add netsurf-gtk to Debian-alternatives if not already there
netsurf='/usr/bin/netsurf-gtk'
for link in x-www-browser gnome-www-browser; do
    if ! update-alternatives --query "$link" | grep -q "$netsurf"; then
        update-alternatives --install "/usr/bin/$link" "$link" "$netsurf" 10
    fi
done
