#!/bin/sh -e
# Copyright (c) 2016 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
if [ "${TARGETNOINSTALL:-c}" = 'c' ] && release -lt jessie -eq kali; then
    error 99 "e17 target is not supported on wheezy/kali."
fi
#REQUIRES='dbar i3status'
DESCRIPTION='Installs the i3 desktop environment.'
HOSTBIN='starti3'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
install i3 dbar i3status

TIPS="$TIPS
You can start i3 via the starti3 host command: sudo starti3
"
