#!/bin/sh -e
# Copyright (c) 2022 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='core'
DESCRIPTION='Fixes xbindkeys error during kali linux setup.'
. "${TARGETSDIR:="$PWD"}/common"


### Append to prepare.sh:

## Debian Overrides
# Kodi wiki recommends using the Jessie Backports repository
if release -eq kali-rolling; then
    cat > '/etc/apt/sources.list.d/kalifix.list' <<EOF
deb http://ftp.halifax.rwth-aachen.de/debian bullseye main non-free contrib
deb-src http://ftp.halifax.rwth-aachen.de/debian bullseye main non-free contrib
EOF
    # Update database
    echo "Update the package list..."
    apt-get update || true
fi

### Install xbindkeys
echo "installing xbindkeys..."
apt -y -qq install xbindkeys xbindkeys-config

# Remove bullseye sources to exclude conflicts with future install steps
echo "Remove bullseye sources..."
rm /etc/apt/sources.list.d/kalifix.list

echo "Update the package list..."
apt-get -y -qq update

#echo -e '\033[1mInstall kali core meta package...'
#apt-get -y -qq install kali-linux-core

#TO-DO: - MOTD FIX (delete lines) /etc/profile.d/kali.sh

TIPS="$TIPS"'
The Kali Linux xbindkeys fix is installed in your chroot.'