#!/bin/sh -e
# Copyright (c) 2022 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='core'
DESCRIPTION='Fixes xbindkeys error during kali linux setup.'

if release -le kali; then

    # Adding debian bullseye repo to get xbindkeys installed
    echo -e '\033[1mAdding debian bullseye repo to sources.list...'
    cat >> /etc/apt/sources.list <<EOF
deb http://ftp.halifax.rwth-aachen.de/debian bullseye main non-free contrib
deb-src http://ftp.halifax.rwth-aachen.de/debian bullseye main non-free contrib
EOF

    # Update the package list.
    # Ignore failures, as most are due to bad PPAs and are not critical.
    echo -e '\033[1mUpdate the package list...'
    apt-get -y -qq update || true

    ### Install xbindkeys
    echo -e '\033[1minstalling xbindkeys...'
    apt -y -qq install xbindkeys xbindkeys-config

    # Remove bullseye sources to exclude conflicts with future install steps
    echo -e '\033[1mRemove bullseye sources...'
    sh -c "head -n -2 /etc/apt/sources.list > /etc/apt/sources.list.tmp"
    rm /etc/apt/sources.list
    mv /etc/apt/sources.list.tmp /etc/apt/sources.list

    echo -e '\033[1mUpdate the package list...'
    apt-get -y -qq update

    echo -e '\033[1mInstall kali core meta package...'
    apt-get -y -qq install kali-linux-core

    #TO-DO: - MOTD FIX (delete lines) /etc/profile.d/kali.sh

    TIPS="$TIPS
    The Kali Linux xbindkeys fix is installed in your chroot."
fi