#!/bin/sh -e
# Copyright (c) 2016 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='x11'
DESCRIPTION='Installs a minimal KDE desktop environment. (Approx. 600MB)'
HOSTBIN='startkde'
CHROOTBIN='crouton-noroot startkde'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
if release -lt vivid then
    PACKNAME='kde-plasma-desktop'
else
    PACKNAME='plasma-desktop'
fi
install --minimal $PACKNAME -- network-manager

TIPS="$TIPS
You can start KDE via the startkde host command: sudo startkde
"
