#!/bin/sh -e
# Copyright (c) 2012 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='x11 core'
DESCRIPTION='Installs the KDE desktop environment. (Approx. 800MB)'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
apt-get -y install kde-standard network-manager-

TIPS="$TIPS
You can start KDE via xinit and the startkde command:
enter-chroot xinit /usr/bin/startkde
"
