#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='kde'
DESCRIPTION='Installs KDE along with common applications. (Approx. 1000MB)'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
install ubuntu=kubuntu-desktop,task-kde-desktop -- network-manager
