#!/bin/sh -e
# Copyright (c) 2017 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
DESCRIPTION='Installs the Kodi media player. (Approx. 140MB)'
HOSTBIN='startkodi'
. "${TARGETSDIR:="$PWD"}/kodi-common"

### Append to prepare.sh:
KODI_NAME='kodi'
### append kodi-common
