#!/bin/sh -e
# Copyright (c) 2016 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='x11'
# We keep the xbmc name for this to avoid duplication
CHROOTETC='xbmc-keyboard.xml xbmc-cycle.py'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:

# Kodi requires the sqlite flag
if [ "${DISTROAKA:-"$DISTRO"}" = 'gentoo' ]; then
    set_flags sqlite
fi

install "$KODI_NAME"

# Configure keymaps kodi/xbmc for the hotkeys ctr-shift-alt F1/F2 to
# cycle through chroots/chromeos. We use ~/.kodi/userdata/keymaps/keyboard.xml
# for this purpose, but the main user may not have been created yet, so we 
# add a script in /etc/profile.d to link ~/.kodi/userdata/keymaps/keyboard.xml
# to /etc/crouton/xbmc-keyboard.xml and likewise for xbmc in ~/.xbmc
profiledsh="/etc/profile.d/crouton-xbmc-keymaps.sh"

# Make sure symbolic link is setup on login
echo '#!/bin/sh' > "$profiledsh"
echo "keyboardxmldir=\"\$HOME/.$KODI_NAME/userdata/keymaps\"" >> "$profiledsh"
echo '# Do not install if user is root, or $HOME does not exist
if [ "`id -u`" -ne 0 -a -d "$HOME" -a ! -e "$keyboardxmldir/keyboard.xml" ]; then
    mkdir -p "$keyboardxmldir"
    ln -sfT /etc/crouton/xbmc-keyboard.xml "$keyboardxmldir/keyboard.xml"
fi' >> "$profiledsh"

chmod 755 "$profiledsh"

TIPS="$TIPS
You can start $KODI_NAME via the start$KODI_NAME host command: sudo start$KODI_NAME
"
