#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='chromium gtk-extra'
DESCRIPTION='Installs the LXDE desktop environment. (Approx. 200MB)'
HOSTBIN='startlxde'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:

# Chromium takes a _very_ long time to build on Gentoo, we're also already
# pulling in the chromium target, so it seems superfluous

install gentoo=lxde-meta,lxde -- gentoo=,dictionaries-common gentoo=,chromium-browser

TIPS="$TIPS
You can start LXDE via the startlxde host command: sudo startlxde
"
