#!/bin/sh -e
# Copyright (c) 2016 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='gtk-extra'
DESCRIPTION='Installs the MATE desktop environment. (Approx. 500MB)'
HOSTBIN='startmate'
CHROOTBIN='crouton-noroot startmate'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
install mate -- dictionaries-common chromium-browser network-manager wicd



TIPS="$TIPS
You can start Mate via the startmate host command: sudo startmate
"
