#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This is a target, but it's not selectable by the user. These are the commands
# that get executed at the very end of the generated prepare.sh.
# These commands are not optional and are automatically added to targets.

REQUIRES=''
DESCRIPTION=''
HOSTBIN='enter-chroot delete-chroot edit-chroot mount-chroot unmount-chroot'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:

# Link the timezone to Chromium OS
# Remove /etc/timezone: this tells Ubuntu/Debian that we are managing the
# content of /etc/localtime manually, and that it should not erase the symbolic
# link upon update, unless "dpkg-reconfigure tzdata" is called explicitly.
rm -f /etc/timezone

# /var/host/timezone/localtime is itself a symbolic link, but as long as the
# zoneinfo packages in the chroot and Chromium OS are the same, it'll be fine
ln -sfT /var/host/timezone/localtime /etc/localtime

# Add the primary user
if ! grep -q ':1000:' /etc/passwd; then
    while ! echo "$username" | grep -q '^[a-z][-a-z0-9_]*$'; do
        if [ -n "$username" ]; then
            echo 'Username must be lowercase letters, numbers, or dashes.' 1>&2
        fi
        echo -n 'Please specify a username for the primary user: ' 1>&2
        read username junk
    done
    useradd -u 1000 -G audio,video,sudo -s '/bin/bash' -m "$username"
    tries=0
    while ! passwd "$username" && [ "$tries" -lt 3 ]; do
        tries="$((tries+1))"
    done
    if [ "$tries" = 3 ]; then
        echo \
"Password left unset. To set a password, inside the chroot run: passwd $username" 1>&2
    fi
fi

echo 'Cleaning up' 1>&2
apt-get clean
rm -f "$0"

if [ -n "$TIPS" ]; then
    echo "
Here's some tips:
$TIPS" 1>&2
fi
