#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
if [ ! "$TARGETS" = 'help' -a ! "${ARCH#arm}" = "$ARCH" ] \
        && ! release -eq precise; then
    error 1 "unity target does not work in xephyr in $RELEASE due to missing egl support."
fi
REQUIRES='gtk-extra'
DESCRIPTION='Installs the Unity desktop environment. (Approx. 700MB)'
HOSTBIN='startunity'
CHROOTBIN='startunity gnome-session-wrapper'
CHROOTETC='unity-indicator-launch'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
install unity unity-2d ubuntu-artwork gnome-session nautilus \
        ubuntu-settings,ubuntu~precise= \
        ubuntu-session,ubuntu~precise+ubuntu~quantal+ubuntu~raring+ubuntu~saucy= \
        -- network-manager brasero firefox

# unity-panel-service launches via upstart in saucy and later, so add desktop file
# to autostart it and any indicators
if release -ge saucy; then
    mkdir -p '/etc/xdg/autostart'
    cat > '/etc/xdg/autostart/crouton-unity-indicator.desktop' <<EOF
[Desktop Entry]
Type=Application
Name=crouton indicator autostart for Unity
Exec=/etc/crouton/unity-indicator-launch
OnlyShowIn=Unity;
NoDisplay=true
StartupNotify=false
Terminal=false
EOF
fi

chmod 755 /etc/crouton/unity-indicator-launch

TIPS="$TIPS
You can start Unity via the startunity host command: sudo startunity
"
