#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
if [ ! "$TARGETS" = 'help' -a ! "${ARCH#arm}" = "$ARCH" ] \
        && ! release -eq precise; then
    error 1 "unity target does not work in xephyr in $RELEASE due to missing egl support."
fi
REQUIRES='gtk-extra'
DESCRIPTION='Installs the Unity desktop environment. (Approx. 700MB)'
HOSTBIN='startunity'
CHROOTBIN='startunity gnome-session-wrapper'
CHROOTETC='unity-xsession'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
install unity unity-2d ubuntu-artwork gnome-session nautilus \
        ubuntu-settings,ubuntu~precise= \
        ubuntu-session,ubuntu~precise+ubuntu~quantal+ubuntu~raring+ubuntu~saucy= \
        -- network-manager brasero firefox

# unity-panel-service launches via upstart in saucy and later, so launch it and any
# indicators manually
if release -ge saucy; then
    ln -sfT '/etc/crouton/unity-xsession' '/etc/X11/Xsession.d/99crouton-unity'
fi

TIPS="$TIPS
You can start Unity via the startunity host command: sudo startunity
"
