#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
if [ "${ARCH#arm}" != "$ARCH" ]; then
    REQUIRES='xephyr'
else
    REQUIRES='xorg'
fi
DESCRIPTION='X11 via autodetected backend. Does not install any desktop environment.'
. "${TARGETSDIR:="$PWD"}/common"
