#!/bin/sh -e
# Copyright (c) 2016 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
if [ -z "$TARGETNOINSTALL" ]; then
    if [ -f /sbin/frecon ]; then
        # Wheezy/Kali are too old to use KMS well
        if release -le wheezy -le kali; then
            REQUIRES='xiwi'
        else
            REQUIRES='xorg'
        fi
    elif grep -q 'SAMSUNG EXYNOS' /proc/cpuinfo; then
        # Xorg won't work on non-freon Samsung ARM devices
        REQUIRES='xiwi'
    else
        REQUIRES='xorg'
    fi
fi
DESCRIPTION='X11 via autodetected backend. Does not install any desktop environment.'
. "${TARGETSDIR:="$PWD"}/common"
