#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This isn't a real target; it's the common commands for installing various
# forms of X11.

### Append to prepare.sh:
# Store and apply the X11 method
ln -sfT "/etc/crouton/xserverrc-$XMETHOD" '/etc/X11/xinit/xserverrc'

# Install utilities and links for powerd-poking daemon
install --minimal gentoo=,xprintidle gentoo=sys-apps/dbus,dbus

ln -sf croutonpowerd /usr/local/bin/gnome-screensaver-command
ln -sf croutonpowerd /usr/local/bin/xscreensaver-command

# Install xbindkeys for key shortcuts
install --minimal xbindkeys

# Add a blank Xauthority to all users' home directories
touch /etc/skel/.Xauthority
chmod 600 /etc/skel/.Xauthority

# Create /usr/share/desktop-directories to avoid issues with xdg-desktop-menu
mkdir -p /usr/share/desktop-directories

# Update policies for mounting and unmounting devices with udisks2
mkdir -p '/etc/polkit-1/localauthority/10-vendor.d'
cat > '/etc/polkit-1/localauthority/10-vendor.d/10-crouton-udisks2.pkla' <<EOF
[Allow mounting when started from crosh]
Identity=*
Action=org.freedesktop.udisks*.filesystem-mount
ResultAny=auth_admin
ResultInactive=yes
ResultActive=yes

[Allow eject when started from crosh]
Identity=*
Action=org.freedesktop.udisks*.*eject*
ResultAny=auth_admin
ResultInactive=yes
ResultActive=yes

[Disallow unmounting of Chromium OS mounts; it won't work]
Identity=*
Action=org.freedesktop.udisks*.filesystem-unmount-others
ResultAny=no
ResultInactive=no
ResultActive=no
EOF
