#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='x11'
DESCRIPTION='Installs the XBMC desktop environment. (Approx. 700MB)'
HOSTBIN='startxbmc'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
apt-get -y install xbmc `noauto network-manager`

TIPS="$TIPS
You can start XBMC via the startxbmc host command: sudo startxbmc
"
