#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='x11'
DESCRIPTION='Installs the XBMC media player. (Approx. 140MB)'
HOSTBIN='startxbmc'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
install xbmc

TIPS="$TIPS
You can start XBMC via the startxbmc host command: sudo startxbmc
"
