#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='core audio'
DESCRIPTION='Nested X11 install. Replaces X11 if specified first.'
CHROOTBIN='croutoncycle croutonpowerd croutonwheel croutonwm croutonxinitrc-wrapper xinit'
CHROOTETC='xbindkeysrc.scm xserverrc-xephyr'
# Prevent X11 from being added if it hasn't already.
echo 'x11' >> "${TARGETDEDUPFILE:-/dev/null}"
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
XMETHOD=xephyr

if release quantal; then
    # As of 2013-01-08, Quantal's Xephyr lacks GLX. Download one manually.
    install_mirror_package 'xserver-xephyr' 'pool/universe/x/xorg-server' \
                           '1\.11\.4-0ubuntu[0-9][0-9]\.[0-9]*'
    # Add the apt preference to avoid immediate upgrade
    cat > /etc/apt/preferences.d/xserver-xephyr <<EOF
Package: xserver-xephyr
Pin: version <1.13.3-0ubuntu4
Pin-Priority: -1
EOF
fi

# xserver-xephyr won't auto replace the manually-downloaded version.
install --minimal \
    xserver-xephyr xinit ratpoison dmz-cursor-theme libgl1-mesa-dri \
    x11-utils x11-xserver-utils xautomation xinput xterm

# Compile croutoncursor
compile cursor '-lX11 -lXfixes -lXrender' \
    libx11-dev libxfixes-dev libxrender-dev

TIPS="$TIPS
You can flip through your running chroot desktops and Chromium OS by hitting
Ctrl+Alt+Shift+Back and Ctrl+Alt+Shift+Forward.
"

### append x11-common
