#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='xfce'
DESCRIPTION='Installs Xfce along with common applications. (Approx. 1200MB)'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
install ubuntu=xubuntu-desktop,task-xfce-desktop -- network-manager xorg
