#!/bin/sh -e
# Copyright (c) 2014 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='gtk-extra'
DESCRIPTION='Installs the Xfce desktop environment. (Approx. 250MB)'
HOSTBIN='startxfce4'
CHROOTBIN='crouton-noroot startxfce4'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
# Ubuntu 12.04 has an old version of Xfce, but there's a PPA for Xfce 4.10.
if release -eq precise && [ "$ARCH" = 'amd64' -o "$ARCH" = 'i386' ]; then
    # Pull in the signing key
    apt-key adv --keyserver 'keyserver.ubuntu.com' \
                --recv-keys '07D44A5424C7C12A4BAB1E80EB563F93142986CE'
    # Add the software source
    cat > '/etc/apt/sources.list.d/xfce-4.10.list' <<EOF
# Bring in Xfce 4.10 on Ubuntu 12.04
deb http://ppa.launchpad.net/xubuntu-dev/xfce-4.10/ubuntu $RELEASE main
deb-src http://ppa.launchpad.net/xubuntu-dev/xfce-4.10/ubuntu $RELEASE main
EOF
    # Update database
    apt-get update
fi

# Fix icons by setting default icon theme to Tango
mkdir -p /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml
cat > '/etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml' <<EOF
<?xml version="1.0" encoding="UTF-8"?>

<channel name="xsettings" version="1.0">
  <property name="Net" type="empty">
    <property name="IconThemeName" type="string" value="Tango"/>
  </property>
</channel>
EOF

install xfce4 xfce4-goodies ubuntu=shimmer-themes, \
        -- dictionaries-common hddtemp xorg

TIPS="$TIPS
You can start Xfce via the startxfce4 host command: sudo startxfce4
"
