#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='chromium gtk-extra'
DESCRIPTION='Installs the Xfce desktop environment. (Approx. 250MB)'
HOSTBIN='startxfce4'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
# Ubuntu 12.04 has an old version of Xfce, but there's a PPA for Xfce 4.10.
if [ "$RELEASE" = 'precise' ] && [ "$ARCH" = 'amd64' -o "$ARCH" = 'i386' ]; then
    # Pull in the signing key
    apt-key adv --keyserver 'keyserver.ubuntu.com' \
                --recv-keys '07D44A5424C7C12A4BAB1E80EB563F93142986CE'
    # Add the software source
    cat > '/etc/apt/sources.list.d/xfce-4.10.list' <<EOF
# Bring in Xfce 4.10 on Ubuntu 12.04
deb http://ppa.launchpad.net/xubuntu-dev/xfce-4.10/ubuntu $RELEASE main
deb-src http://ppa.launchpad.net/xubuntu-dev/xfce-4.10/ubuntu $RELEASE main
EOF
    # Update database
    apt-get update
fi


if [ "${DISTROAKA:-"$DISTRO"}" = 'gentoo' ]; then
# Set XFCE profile if available
    PROFILE_ACTION="set"
    if [ $RELEASE = "funtoo" ]; then
        PROFILE_ACTION="add"
    fi
    GENTOO_PROFILE=$"`eselect profile list | grep xfce | grep -P -o '(?<=\[)[0-9]*(?=\])'`"
    if [ -n $GENTOO_PROFILE ]; then
        eselect profile "$PROFILE_ACTION" "$GENTOO_PROFILE"
    fi
fi

install gentoo=xfce4-meta,xfce4 gentoo=,xfce4-goodies ubuntu=shimmer-themes, \
        -- gentoo=,dictionaries-common hddtemp gentoo=xorg-x11,xorg


TIPS="$TIPS
You can start Xfce via the startxfce4 host command: sudo startxfce4
"
