#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='xfce'
DESCRIPTION='Installs Xfce along with common applications. (Approx. 1200MB)'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
# Avoid /etc/skel/.xscreensaver conflicts
xsvr='/etc/skel/.xscreensaver'
[ -f "$xsvr" ] && mv -f "$xsvr" "$xsvr.bak"
install arch=xfce-goodies,ubuntu=xubuntu-desktop,task-xfce-desktop \
        -- network-manager xorg
[ -f "$xsvr.bak" ] && mv -f "$xsvr.bak" "$xsvr"

