#!/bin/sh -e
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
if [ "$TARGETS" != 'help' -a "${ARCH#arm}" != "$ARCH" ]; then
    error 1 'xorg target does not work on ARM.'
fi
REQUIRES='core audio'
PROVIDES='x11'
DESCRIPTION='X.Org X11 backend. Enables GPU acceleration on supported platforms.'
CHROOTBIN='brightness croutoncycle croutonpowerd croutonxinitrc-wrapper setres xinit'
CHROOTETC='xbindkeysrc.scm xserverrc-x11 xserverrc-local.example'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
XMETHOD="${XMETHOD:-x11}"

# On precise, install lts-saucy xorg server to support newer hardware if kernel
# version != 3.4 (lts-saucy mesa requires version >=3.6)
if release -eq precise && ! uname -r | grep -q "^3.4."; then
    # We still install xorg later to pull in its dependencies
    install --minimal xserver-xorg-lts-saucy libgl1-mesa-glx-lts-saucy \
        xserver-xorg-input-synaptics-lts-saucy
fi

install xorg dmz-cursor-theme
# Fix launching X11 from inside crosh (user doesn't own a TTY)
sed -i 's/allowed_users=.*/allowed_users=anybody/' '/etc/X11/Xwrapper.config'

TIPS="$TIPS
You can flip through your running chroot desktops and Chromium OS by hitting
Ctrl+Alt+Shift+Back and Ctrl+Alt+Shift+Forward.
"

### append x11-common
