#!/bin/sh -e
# Copyright (c) 2014 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
if [ "$TARGETS" != 'help' -a "${ARCH#arm}" != "$ARCH" ]; then
    error 1 'xorg target does not work on ARM.'
fi
REQUIRES='core audio'
PROVIDES='x11'
DESCRIPTION='X.Org X11 backend. Enables GPU acceleration on supported platforms.'
CHROOTBIN='brightness croutoncycle croutonpowerd croutonxinitrc-wrapper setres xinit'
CHROOTETC='xbindkeysrc.scm xserverrc-x11 xserverrc-local.example'
. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
XMETHOD="${XMETHOD:-x11}"

# On precise, install lts-trusty xorg server to support newer hardware if kernel
# version != 3.4 (lts-trusty mesa requires version >=3.6)
if release -eq precise && ! uname -r | grep -q "^3.4."; then
    # We still install xorg later to pull in its dependencies
    install --minimal xserver-xorg-lts-trusty libgl1-mesa-glx-lts-trusty \
        xserver-xorg-input-synaptics-lts-trusty
fi

# On saucy/jessie onwards, if kernel version is 3.4, manually pin down old mesa
# libraries, as new ones require version >=3.6 (see issue #704).
# This is only required on non-Atom Intel chipsets (Atom uses i915 dri driver)
if release -ge saucy -ge jessie && uname -r | grep -q "^3.4." &&
        grep -q 0x8086 /sys/class/graphics/fb0/device/vendor 2>/dev/null &&
        ! grep -q 0xa0 /sys/class/graphics/fb0/device/device 2>/dev/null; then
    # Create a dummy libwayland-egl1 package, to satisfy dependencies
    # (the libraries are actually provided by libegl1-mesa-drivers in precise)
    install --minimal --asdeps equivs

    DEBTMP="`mktemp -d crouton.XXXXXX --tmpdir=/tmp`"
    addtrap "rm -rf --one-file-system '$DEBTMP'"

    ( cd "$DEBTMP"; equivs-build - ) <<END
Section: misc
Priority: optional
Standards-Version: 3.9.2

Package: libwayland-egl1-dummy
Version: 8.0.4
Depends: libegl1-mesa-drivers
Provides: libwayland-egl1
Description: Dummy package providing libwayland-egl1
END

    # Add precise package sources
    mirror="`detect_mirror`"

    if release -ge saucy; then
        oldrelease="precise"

        cat > "/etc/apt/sources.list.d/$oldrelease.list" <<END
deb $mirror $oldrelease main
deb $mirror $oldrelease-updates main
deb $mirror $oldrelease-security main
END
    elif release -ge jessie; then
        oldrelease="wheezy"

        cat > "/etc/apt/sources.list.d/$oldrelease.list" <<END
deb $mirror $oldrelease main
END
    fi

    cat > "/etc/apt/preferences.d/${oldrelease}-mesa-pin" <<END
# Do not install any packages from $oldrelease by default
Package: *
Pin: release n=$oldrelease
Pin-Priority: -10

# Install mesa packages and their dependencies from precise
Package: libegl1-mesa:* libegl1-mesa-dbg:* libegl1-mesa-dev:* \
         libegl1-mesa-drivers:* libegl1-mesa-drivers-dbg:* \
         libgl1-mesa-dev:* libgl1-mesa-dri:* libgl1-mesa-dri-dbg:* \
         libgl1-mesa-glx:* libgl1-mesa-glx-dbg:* \
         libglapi-mesa:* libglapi-mesa-dbg:* \
         libgles1-mesa:* libgles1-mesa-dbg:* libgles1-mesa-dev:* \
         libgles2-mesa:* libgles2-mesa-dbg:* libgles2-mesa-dev:* \
         libdrm-nouveau1a:* libllvm3.0:* libudev0:* libffi5:*
Pin: release n=$oldrelease
Pin-Priority: 1100
END

    if release -ge jessie; then
        cat >> "/etc/apt/preferences.d/${oldrelease}-mesa-pin" <<END

# Prevent upgrading of libegl1-mesa*: we want to do this manually
# to "unbreak" libwayland0 dependency
Package: libegl1-mesa:* libegl1-mesa-drivers:*
Pin: version <10
Pin-Priority: -1
END
    fi

    # Fetch new package sources
    apt-get update

    # Debian needs special handling as old packages depend on
    # libwayland0=0.85.0-2
    if release -ge jessie; then
        # Note: we only install native packages here. It's unlikely i386
        # packages would require EGL anyway (e.g. Steam does not)
        ( cd "$DEBTMP"; apt-get download libegl1-mesa libegl1-mesa-drivers )
        dpkg -i --force-depends --force-breaks "$DEBTMP"/libegl1-mesa*.deb
        # Hack the package database to replace broken dependency
        sed -i -e 's/libwayland0 (= 0.85.0-2)/libwayland-client0/' \
            /var/lib/dpkg/status
    fi

    # Forcibly replace libwayland-egl1-mesa by libwayland-egl1-dummy
    # (dpkg -r does not fail if package does not exist)
    dpkg -r --force-depends libwayland-egl1-mesa libwayland-egl1-mesa:i386
    dpkg -i --force-depends "$DEBTMP"/libwayland-egl1-dummy_*_all.deb

    # Downgrade packages, -f is needed as dependencies are broken
    # On Ubuntu, this happens to install python2.7-minimal as well, pulled in
    # by a wrong dependency of ubuntu-minimal-1.267 (precise), which we did
    # not install.
    # Looks like an apt bug, I guess we can live with that.
    apt-get -y --force-yes --no-install-recommends dist-upgrade -f
fi

install xorg dmz-cursor-theme
# Fix launching X11 from inside crosh (user doesn't own a TTY)
sed -i 's/allowed_users=.*/allowed_users=anybody/' '/etc/X11/Xwrapper.config'

TIPS="$TIPS
You can flip through your running chroot desktops and Chromium OS by hitting
Ctrl+Alt+Shift+Back and Ctrl+Alt+Shift+Forward.
"

### append x11-common
