#!/bin/sh -e
# Copyright (c) 2014 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# This file contains functions common to many of the scripts.
# The file is sourced when the scripts are run directly out of the repo, and
# directly inserted into the files when built into a bundle.

. "$SCRIPTDIR/parts/common"
from parts/installer import installscript, release
import trap, output
import getopts
from parts/os import disablehungtask
import path
import websocket
